type ManualPracticeLocale = "ru" | "uk" | "fa" | "ar" | "fr" | "es" | "it" | "pl";

export const PRACTICE_MEANING_OVERRIDES: Record<
  string,
  Partial<Record<ManualPracticeLocale, string>>
> = {
  "I see the man in the park.": {
    ru: "Я вижу мужчину в парке.",
    uk: "Я бачу чоловіка в парку.",
    fa: "من مرد را در پارک می‌بینم.",
    ar: "أرى الرجل في الحديقة.",
    fr: "Je vois l'homme dans le parc.",
    es: "Veo al hombre en el parque.",
    it: "Vedo l'uomo nel parco.",
    pl: "Widzę mężczyznę w parku.",
  },
  "We are visiting the female friend in the evening.": {
    ru: "Мы навещаем подругу вечером.",
    uk: "Ми навідуємо подругу ввечері.",
    fa: "ما عصر به دیدن دوست زن می‌رویم.",
    ar: "نحن نزور الصديقة في المساء.",
    fr: "Nous rendons visite à l'amie le soir.",
    es: "Visitamos a la amiga por la tarde.",
    it: "Andiamo a trovare l'amica la sera.",
    pl: "Odwiedzamy przyjaciółkę wieczorem.",
  },
  "The gift is for the child.": {
    ru: "Подарок для ребёнка.",
    uk: "Подарунок для дитини.",
    fa: "این هدیه برای کودک است.",
    ar: "الهدية للطفل.",
    fr: "Le cadeau est pour l'enfant.",
    es: "El regalo es para el niño.",
    it: "Il regalo è per il bambino.",
    pl: "Prezent jest dla dziecka.",
  },
  "I go to work by bus.": {
    ru: "Я еду на работу на автобусе.",
    uk: "Я їду на роботу автобусом.",
    fa: "من با اتوبوس به محل کار می‌روم.",
    ar: "أذهب إلى العمل بالحافلة.",
    fr: "Je vais au travail en bus.",
    es: "Voy al trabajo en autobús.",
    it: "Vado al lavoro in autobus.",
    pl: "Jadę do pracy autobusem.",
  },
  "He helps the woman with the form.": {
    ru: "Он помогает женщине с формой.",
    uk: "Він допомагає жінці з формуляром.",
    fa: "او به زن با فرم کمک می‌کند.",
    ar: "هو يساعد المرأة في الاستمارة.",
    fr: "Il aide la femme avec le formulaire.",
    es: "Él ayuda a la mujer con el formulario.",
    it: "Lui aiuta la donna con il modulo.",
    pl: "On pomaga kobiecie z formularzem.",
  },
  "We are going to the station.": {
    ru: "Мы идём к вокзалу.",
    uk: "Ми йдемо до вокзалу.",
    fa: "ما به ایستگاه می‌رویم.",
    ar: "نحن ذاهبون إلى المحطة.",
    fr: "Nous allons à la gare.",
    es: "Vamos a la estación.",
    it: "Andiamo alla stazione.",
    pl: "Idziemy na dworzec.",
  },
  "She buys the apple in the supermarket.": {
    ru: "Она покупает яблоко в супермаркете.",
    uk: "Вона купує яблуко в супермаркеті.",
    fa: "او سیب را در سوپرمارکت می‌خرد.",
    ar: "هي تشتري التفاحة في السوبرماركت.",
    fr: "Elle achète la pomme au supermarché.",
    es: "Ella compra la manzana en el supermercado.",
    it: "Lei compra la mela al supermercato.",
    pl: "Ona kupuje jabłko w supermarkecie.",
  },
  "I put the lamp onto the table.": {
    ru: "Я ставлю лампу на стол.",
    uk: "Я ставлю лампу на стіл.",
    fa: "من چراغ را روی میز می‌گذارم.",
    ar: "أضع المصباح على الطاولة.",
    fr: "Je pose la lampe sur la table.",
    es: "Pongo la lámpara sobre la mesa.",
    it: "Metto la lampada sul tavolo.",
    pl: "Kładę lampę na stół.",
  },
  "The lamp is standing on the table.": {
    ru: "Лампа стоит на столе.",
    uk: "Лампа стоїть на столі.",
    fa: "چراغ روی میز قرار دارد.",
    ar: "المصباح موجود على الطاولة.",
    fr: "La lampe est sur la table.",
    es: "La lámpara está sobre la mesa.",
    it: "La lampada è sul tavolo.",
    pl: "Lampa stoi na stole.",
  },
  "We are going into the kitchen.": {
    ru: "Мы идём на кухню.",
    uk: "Ми йдемо на кухню.",
    fa: "ما به آشپزخانه می‌رویم.",
    ar: "نحن ندخل إلى المطبخ.",
    fr: "Nous allons dans la cuisine.",
    es: "Vamos a la cocina.",
    it: "Andiamo in cucina.",
    pl: "Idziemy do kuchni.",
  },
  "We study in the kitchen.": {
    ru: "Мы занимаемся на кухне.",
    uk: "Ми навчаємося на кухні.",
    fa: "ما در آشپزخانه درس می‌خوانیم.",
    ar: "نحن ندرس في المطبخ.",
    fr: "Nous étudions dans la cuisine.",
    es: "Estudiamos en la cocina.",
    it: "Studiamo in cucina.",
    pl: "Uczymy się w kuchni.",
  },
  "He hangs the photo onto the wall.": {
    ru: "Он вешает фотографию на стену.",
    uk: "Він вішає фото на стіну.",
    fa: "او عکس را روی دیوار آویزان می‌کند.",
    ar: "هو يعلّق الصورة على الحائط.",
    fr: "Il accroche la photo au mur.",
    es: "Él cuelga la foto en la pared.",
    it: "Lui appende la foto al muro.",
    pl: "On wiesza zdjęcie na ścianie.",
  },
  "The photo is hanging on the wall.": {
    ru: "Фотография висит на стене.",
    uk: "Фото висить на стіні.",
    fa: "عکس روی دیوار آویزان است.",
    ar: "الصورة معلّقة على الحائط.",
    fr: "La photo est accrochée au mur.",
    es: "La foto está colgada en la pared.",
    it: "La foto è appesa al muro.",
    pl: "Zdjęcie wisi na ścianie.",
  },
  "The teacher explains the rule to the student.": {
    ru: "Учитель объясняет правило ученику.",
    uk: "Учитель пояснює правило учневі.",
    fa: "معلم قانون را برای دانش‌آموز توضیح می‌دهد.",
    ar: "يشرح المعلم القاعدة للطالب.",
    fr: "Le professeur explique la règle à l'élève.",
    es: "El profesor explica la regla al estudiante.",
    it: "L'insegnante spiega la regola allo studente.",
    pl: "Nauczyciel wyjaśnia zasadę uczniowi.",
  },
  "We are waiting for the bus.": {
    ru: "Мы ждём автобус.",
    uk: "Ми чекаємо на автобус.",
    fa: "ما منتظر اتوبوس هستیم.",
    ar: "نحن ننتظر الحافلة.",
    fr: "Nous attendons le bus.",
    es: "Estamos esperando el autobús.",
    it: "Stiamo aspettando l'autobus.",
    pl: "Czekamy na autobus.",
  },
  "She is speaking with the doctor about the appointment.": {
    ru: "Она разговаривает с врачом о приёме.",
    uk: "Вона розмовляє з лікарем про запис на прийом.",
    fa: "او با پزشک درباره وقت ملاقات صحبت می‌کند.",
    ar: "هي تتحدث مع الطبيب عن الموعد.",
    fr: "Elle parle avec le médecin du rendez-vous.",
    es: "Ella habla con el médico sobre la cita.",
    it: "Lei parla con il medico dell'appuntamento.",
    pl: "Ona rozmawia z lekarzem o terminie wizyty.",
  },
  "I give the child a book.": {
    ru: "Я даю ребёнку книгу.",
    uk: "Я даю дитині книжку.",
    fa: "من به کودک یک کتاب می‌دهم.",
    ar: "أعطي الطفل كتابًا.",
    fr: "Je donne un livre à l'enfant.",
    es: "Le doy un libro al niño.",
    it: "Do un libro al bambino.",
    pl: "Daję dziecku książkę.",
  },
  "Because of the problem, I am coming later.": {
    ru: "Из-за проблемы я приду позже.",
    uk: "Через проблему я прийду пізніше.",
    fa: "به خاطر این مشکل دیرتر می‌آیم.",
    ar: "بسبب المشكلة سأصل لاحقًا.",
    fr: "À cause du problème, j'arrive plus tard.",
    es: "Debido al problema, llegaré más tarde.",
    it: "A causa del problema, arrivo più tardi.",
    pl: "Z powodu problemu przyjdę później.",
  },
  "In spite of the rain, we are going for a walk.": {
    ru: "Несмотря на дождь, мы идём гулять.",
    uk: "Попри дощ, ми йдемо на прогулянку.",
    fa: "با وجود باران، ما برای پیاده‌روی می‌رویم.",
    ar: "على الرغم من المطر، نحن ذاهبون في نزهة.",
    fr: "Malgré la pluie, nous allons nous promener.",
    es: "A pesar de la lluvia, vamos a dar un paseo.",
    it: "Nonostante la pioggia, andiamo a fare una passeggiata.",
    pl: "Pomimo deszczu idziemy na spacer.",
  },
  "That is the new colleague's car.": {
    ru: "Это машина нового коллеги.",
    uk: "Це машина нового колеги.",
    fa: "این ماشین همکار جدید است.",
    ar: "هذه سيارة الزميل الجديد.",
    fr: "C'est la voiture du nouveau collègue.",
    es: "Ese es el coche del nuevo compañero.",
    it: "Quella è l'auto del nuovo collega.",
    pl: "To jest samochód nowego kolegi.",
  },
  "I remember the first day in Berlin.": {
    ru: "Я помню первый день в Берлине.",
    uk: "Я пам’ятаю перший день у Берліні.",
    fa: "من اولین روز در برلین را به یاد دارم.",
    ar: "أتذكر اليوم الأول في برلين.",
    fr: "Je me souviens du premier jour à Berlin.",
    es: "Recuerdo el primer día en Berlín.",
    it: "Mi ricordo del primo giorno a Berlino.",
    pl: "Pamiętam pierwszy dzień w Berlinie.",
  },
  "She thanks the nice neighbor.": {
    ru: "Она благодарит приятного соседа.",
    uk: "Вона дякує привітному сусідові.",
    fa: "او از همسایه مهربان تشکر می‌کند.",
    ar: "هي تشكر الجار اللطيف.",
    fr: "Elle remercie le gentil voisin.",
    es: "Ella le da las gracias al amable vecino.",
    it: "Lei ringrazia il gentile vicino.",
    pl: "Ona dziękuje miłemu sąsiadowi.",
  },
  "During the course, the phones are off.": {
    ru: "Во время курса телефоны выключены.",
    uk: "Під час курсу телефони вимкнені.",
    fa: "در طول دوره، تلفن‌ها خاموش هستند.",
    ar: "أثناء الدورة تكون الهواتف مطفأة.",
    fr: "Pendant le cours, les téléphones sont éteints.",
    es: "Durante el curso, los teléfonos están apagados.",
    it: "Durante il corso, i telefoni sono spenti.",
    pl: "Podczas kursu telefony są wyłączone.",
  },
  "Instead of the car, we are taking the train.": {
    ru: "Вместо машины мы едем на поезде.",
    uk: "Замість машини ми їдемо потягом.",
    fa: "به جای ماشین، ما با قطار می‌رویم.",
    ar: "بدلاً من السيارة سنأخذ القطار.",
    fr: "Au lieu de la voiture, nous prenons le train.",
    es: "En lugar del coche, vamos en tren.",
    it: "Invece della macchina, prendiamo il treno.",
    pl: "Zamiast samochodu jedziemy pociągiem.",
  },
  "Sofia asks Omar what he would like to drink.": {
    ru: "София спрашивает Омара, что он хотел бы выпить.",
    uk: "Софія запитує Омара, що він хотів би випити.",
    fa: "سوفیا از عمر می‌پرسد چه چیزی دوست دارد بنوشد.",
    ar: "تسأل صوفيا عمر ماذا يود أن يشرب.",
    fr: "Sofia demande à Omar ce qu'il voudrait boire.",
    es: "Sofía le pregunta a Omar qué le gustaría beber.",
    it: "Sofia chiede a Omar che cosa vorrebbe bere.",
    pl: "Sofia pyta Omara, co chciałby wypić.",
  },
  "Mina asks Omar whether the seat is free.": {
    ru: "Мина спрашивает Омара, свободно ли это место.",
    uk: "Міна запитує Омара, чи вільне це місце.",
    fa: "مینا از عمر می‌پرسد آیا این صندلی خالی است.",
    ar: "تسأل مينا عمر إن كان هذا المقعد شاغرًا.",
    fr: "Mina demande à Omar si cette place est libre.",
    es: "Mina le pregunta a Omar si este asiento está libre.",
    it: "Mina chiede a Omar se questo posto è libero.",
    pl: "Mina pyta Omara, czy to miejsce jest wolne.",
  },
  "Sofia asks whether they are here for the first time.": {
    ru: "София спрашивает, впервые ли они здесь.",
    uk: "Софія запитує, чи вони тут уперше.",
    fa: "سوفیا می‌پرسد آیا آن‌ها اولین بار است که اینجا هستند.",
    ar: "تسأل صوفيا ما إذا كانت هذه هي المرة الأولى لهما هنا.",
    fr: "Sofia demande si c'est leur première fois ici.",
    es: "Sofía pregunta si es la primera vez que están aquí.",
    it: "Sofia chiede se è la loro prima volta qui.",
    pl: "Sofia pyta, czy są tu po raz pierwszy.",
  },
  "Omar wants to practice together and asks Mina about her German.": {
    ru: "Омар хочет заниматься вместе и спрашивает Мину о её немецком.",
    uk: "Омар хоче практикуватися разом і запитує Міну про її німецьку.",
    fa: "عمر می‌خواهد با هم تمرین کند و از مینا درباره آلمانی‌اش می‌پرسد.",
    ar: "يريد عمر أن يتدرّبا معًا ويسأل مينا عن مستواها في الألمانية.",
    fr: "Omar veut s'entraîner ensemble et demande à Mina comment va son allemand.",
    es: "Omar quiere practicar juntos y le pregunta a Mina por su alemán.",
    it: "Omar vuole esercitarsi insieme e chiede a Mina del suo tedesco.",
    pl: "Omar chce ćwiczyć razem i pyta Minę o jej niemiecki.",
  },
  "After an hour, Sofia asks whether they want to order anything else.": {
    ru: "Через час София спрашивает, хотят ли они заказать что-нибудь ещё.",
    uk: "Через годину Софія запитує, чи хочуть вони замовити ще щось.",
    fa: "بعد از یک ساعت، سوفیا می‌پرسد آیا آن‌ها چیز دیگری هم می‌خواهند سفارش دهند.",
    ar: "بعد ساعة تسأل صوفيا إن كانوا يريدون طلب شيء آخر.",
    fr: "Après une heure, Sofia demande s'ils veulent commander autre chose.",
    es: "Después de una hora, Sofía pregunta si quieren pedir algo más.",
    it: "Dopo un'ora Sofia chiede se vogliono ordinare qualcos'altro.",
    pl: "Po godzinie Sofia pyta, czy chcą zamówić coś jeszcze.",
  },
  "When leaving, Mina asks whether Omar is coming again tomorrow.": {
    ru: "Уходя, Мина спрашивает, придёт ли Омар снова завтра.",
    uk: "Коли вони йдуть, Міна запитує, чи прийде Омар знову завтра.",
    fa: "هنگام رفتن، مینا می‌پرسد آیا عمر فردا دوباره می‌آید.",
    ar: "عند المغادرة تسأل مينا إن كان عمر سيأتي مرة أخرى غدًا.",
    fr: "En partant, Mina demande si Omar revient demain.",
    es: "Al irse, Mina pregunta si Omar volverá mañana.",
    it: "Quando se ne vanno, Mina chiede se Omar tornerà domani.",
    pl: "Przy wyjściu Mina pyta, czy Omar przyjdzie znowu jutro.",
  },
  "Amir says his train will arrive in five minutes.": {
    ru: "Амир говорит, что его поезд прибудет через пять минут.",
    uk: "Амір каже, що його потяг прибуде за п’ять хвилин.",
    fa: "امیر می‌گوید قطارش تا پنج دقیقه دیگر می‌رسد.",
    ar: "يقول أمير إن قطاره سيصل بعد خمس دقائق.",
    fr: "Amir dit que son train arrivera dans cinq minutes.",
    es: "Amir dice que su tren llegará en cinco minutos.",
    it: "Amir dice che il suo treno arriverà tra cinque minuti.",
    pl: "Amir mówi, że jego pociąg przyjedzie za pięć minut.",
  },
  "Amir asks what Lena is wearing so he can find her.": {
    ru: "Амир спрашивает, во что одета Лена, чтобы он мог её найти.",
    uk: "Амір запитує, у що одягнена Лена, щоб він міг її знайти.",
    fa: "امیر می‌پرسد لنا چه پوشیده است تا بتواند او را پیدا کند.",
    ar: "يسأل أمير ماذا ترتدي لينا لكي يتمكن من العثور عليها.",
    fr: "Amir demande ce que Lena porte pour pouvoir la trouver.",
    es: "Amir pregunta qué lleva puesto Lena para poder encontrarla.",
    it: "Amir chiede cosa indossa Lena per poterla trovare.",
    pl: "Amir pyta, co ma na sobie Lena, żeby mógł ją znaleźć.",
  },
  "A little later, the platform changes on the board.": {
    ru: "Немного позже на табло меняется платформа.",
    uk: "Трохи пізніше на табло змінюється колія.",
    fa: "کمی بعد، سکوی حرکت روی تابلو تغییر می‌کند.",
    ar: "بعد قليل يتغيّر الرصيف على اللوحة.",
    fr: "Un peu plus tard, le quai change sur le tableau d'affichage.",
    es: "Poco después, el andén cambia en el panel.",
    it: "Poco dopo, il binario cambia sul tabellone.",
    pl: "Chwilę później na tablicy zmienia się peron.",
  },
  "Amir finds Lena and asks whether they should go to the bus now.": {
    ru: "Амир находит Лену и спрашивает, не пойти ли им сейчас к автобусу.",
    uk: "Амір знаходить Лену й питає, чи не варто їм зараз іти до автобуса.",
    fa: "امیر لنا را پیدا می‌کند و می‌پرسد آیا حالا باید به سمت اتوبوس بروند.",
    ar: "يعثر أمير على لينا ويسأل إن كان عليهما الذهاب إلى الحافلة الآن.",
    fr: "Amir retrouve Lena et demande s'ils devraient aller au bus maintenant.",
    es: "Amir encuentra a Lena y pregunta si deberían ir al autobús ahora.",
    it: "Amir trova Lena e chiede se dovrebbero andare all'autobus adesso.",
    pl: "Amir znajduje Lenę i pyta, czy powinni teraz iść do autobusu.",
  },
  "Amir wants to buy a ticket first.": {
    ru: "Амир хочет сначала купить билет.",
    uk: "Амір хоче спочатку купити квиток.",
    fa: "امیر می‌خواهد اول یک بلیت بخرد.",
    ar: "يريد أمير أن يشتري تذكرة أولاً.",
    fr: "Amir veut d'abord acheter un billet.",
    es: "Amir quiere comprar primero un billete.",
    it: "Amir vuole comprare prima un biglietto.",
    pl: "Amir chce najpierw kupić bilet.",
  },
  "After that, both walk together to the bus stop.": {
    ru: "После этого они вместе идут к автобусной остановке.",
    uk: "Після цього вони разом ідуть до автобусної зупинки.",
    fa: "بعد از آن، هر دو با هم تا ایستگاه اتوبوس می‌روند.",
    ar: "بعد ذلك يسيران معًا إلى موقف الحافلة.",
    fr: "Après cela, ils vont ensemble à l'arrêt de bus.",
    es: "Después de eso, los dos van juntos a la parada de autobús.",
    it: "Dopo di che, vanno insieme alla fermata dell'autobus.",
    pl: "Potem oboje idą razem na przystanek autobusowy.",
  },
  "The teacher asks Daria to introduce herself.": {
    ru: "Учитель просит Дарию представиться.",
    uk: "Учитель просить Дарію представитися.",
    fa: "معلم از داریا می‌خواهد خودش را معرفی کند.",
    ar: "يطلب المعلم من داريا أن تقدّم نفسها.",
    fr: "Le professeur demande à Daria de se présenter.",
    es: "El profesor le pide a Daria que se presente.",
    it: "L'insegnante chiede a Daria di presentarsi.",
    pl: "Nauczyciel prosi Darię, żeby się przedstawiła.",
  },
  "During the break, Marta asks whether the seat is free.": {
    ru: "Во время перерыва Марта спрашивает, свободно ли это место.",
    uk: "Під час перерви Марта запитує, чи вільне це місце.",
    fa: "در زمان استراحت، مارتا می‌پرسد آیا این صندلی خالی است.",
    ar: "أثناء الاستراحة تسأل مارتا إن كان هذا المقعد شاغرًا.",
    fr: "Pendant la pause, Marta demande si cette place est libre.",
    es: "Durante la pausa, Marta pregunta si este asiento está libre.",
    it: "Durante la pausa, Marta chiede se questo posto è libero.",
    pl: "Podczas przerwy Marta pyta, czy to miejsce jest wolne.",
  },
  "Marta asks which languages Daria speaks.": {
    ru: "Марта спрашивает, на каких языках говорит Дария.",
    uk: "Марта запитує, якими мовами говорить Дарія.",
    fa: "مارتا می‌پرسد داریا به چه زبان‌هایی صحبت می‌کند.",
    ar: "تسأل مارتا ما اللغات التي تتحدث بها داريا.",
    fr: "Marta demande quelles langues parle Daria.",
    es: "Marta pregunta qué idiomas habla Daria.",
    it: "Marta chiede quali lingue parla Daria.",
    pl: "Marta pyta, jakimi językami mówi Daria.",
  },
  "The teacher gives homework for tomorrow.": {
    ru: "Учитель задаёт домашнее задание на завтра.",
    uk: "Учитель задає домашнє завдання на завтра.",
    fa: "معلم برای فردا تکلیف می‌دهد.",
    ar: "المعلم يعطي واجبًا منزليًا للغد.",
    fr: "Le professeur donne des devoirs pour demain.",
    es: "El profesor manda tarea para mañana.",
    it: "L'insegnante assegna i compiti per domani.",
    pl: "Nauczyciel zadaje pracę domową na jutro.",
  },
  "After class, Marta wants to study together.": {
    ru: "После занятий Марта хочет позаниматься вместе.",
    uk: "Після занять Марта хоче повчитися разом.",
    fa: "بعد از کلاس، مارتا می‌خواهد با هم درس بخوانند.",
    ar: "بعد الدرس تريد مارتا أن يدرسا معًا.",
    fr: "Après le cours, Marta veut étudier ensemble.",
    es: "Después de clase, Marta quiere estudiar juntas.",
    it: "Dopo le lezioni Marta vuole studiare insieme.",
    pl: "Po zajęciach Marta chce uczyć się razem.",
  },
  "At the end of the day, Daria writes to her sister about the course.": {
    ru: "В конце дня Дария пишет сестре о курсе.",
    uk: "Наприкінці дня Дарія пише сестрі про курс.",
    fa: "در پایان روز، داریا برای خواهرش درباره دوره می‌نویسد.",
    ar: "في نهاية اليوم تكتب داريا لأختها عن الدورة.",
    fr: "À la fin de la journée, Daria écrit à sa sœur au sujet du cours.",
    es: "Al final del día, Daria le escribe a su hermana sobre el curso.",
    it: "Alla fine della giornata Daria scrive a sua sorella del corso.",
    pl: "Pod koniec dnia Daria pisze do siostry o kursie.",
  },
  "The waiter asks for their drink order.": {
    ru: "Официант спрашивает их заказ на напитки.",
    uk: "Офіціант запитує їхнє замовлення на напої.",
    fa: "پیشخدمت سفارش نوشیدنی آن‌ها را می‌پرسد.",
    ar: "يسأل النادل عن طلب المشروبات الخاص بهما.",
    fr: "Le serveur demande leur commande de boissons.",
    es: "El camarero pregunta qué bebidas quieren pedir.",
    it: "Il cameriere chiede la loro ordinazione delle bevande.",
    pl: "Kelner pyta o ich zamówienie na napoje.",
  },
  "Leila receives a pizza instead of her pasta.": {
    ru: "Лейла получает пиццу вместо своей пасты.",
    uk: "Лейла отримує піцу замість своєї пасти.",
    fa: "لیلا به جای پاستایش یک پیتزا دریافت می‌کند.",
    ar: "تتلقى ليلى بيتزا بدلًا من المعكرونة الخاصة بها.",
    fr: "Leila reçoit une pizza au lieu de ses pâtes.",
    es: "Leila recibe una pizza en lugar de su pasta.",
    it: "Leila riceve una pizza invece della sua pasta.",
    pl: "Leila dostaje pizzę zamiast swojego makaronu.",
  },
  "The waiter apologizes and asks whether Leila wants to wait.": {
    ru: "Официант извиняется и спрашивает, хочет ли Лейла подождать.",
    uk: "Офіціант вибачається й запитує, чи хоче Лейла почекати.",
    fa: "پیشخدمت عذرخواهی می‌کند و می‌پرسد آیا لیلا می‌خواهد صبر کند.",
    ar: "يعتذر النادل ويسأل إن كانت ليلى تريد الانتظار.",
    fr: "Le serveur s'excuse et demande si Leila veut attendre.",
    es: "El camarero se disculpa y pregunta si Leila quiere esperar.",
    it: "Il cameriere si scusa e chiede se Leila vuole aspettare.",
    pl: "Kelner przeprasza i pyta, czy Leila chce poczekać.",
  },
  "Paolo notices one extra drink on the bill.": {
    ru: "Паоло замечает в счёте один лишний напиток.",
    uk: "Паоло помічає в рахунку один зайвий напій.",
    fa: "پائولو یک نوشیدنی اضافه روی صورت‌حساب می‌بیند.",
    ar: "يلاحظ باولو مشروبًا إضافيًا واحدًا في الفاتورة.",
    fr: "Paolo remarque une boisson en trop sur l'addition.",
    es: "Paolo nota una bebida extra en la cuenta.",
    it: "Paolo nota una bevanda in più sul conto.",
    pl: "Paolo zauważa jeden dodatkowy napój na rachunku.",
  },
  "The waiter fixes the mistake and brings a new bill.": {
    ru: "Официант исправляет ошибку и приносит новый счёт.",
    uk: "Офіціант виправляє помилку й приносить новий рахунок.",
    fa: "پیشخدمت اشتباه را اصلاح می‌کند و یک صورت‌حساب جدید می‌آورد.",
    ar: "يصحح النادل الخطأ ويجلب فاتورة جديدة.",
    fr: "Le serveur corrige l'erreur et apporte une nouvelle addition.",
    es: "El camarero corrige el error y trae una nueva cuenta.",
    it: "Il cameriere corregge l'errore e porta un nuovo conto.",
    pl: "Kelner poprawia błąd i przynosi nowy rachunek.",
  },
  "When leaving, the waiter asks whether they would like to come again.": {
    ru: "При уходе официант спрашивает, хотели бы они прийти ещё раз.",
    uk: "Коли вони йдуть, офіціант запитує, чи хотіли б вони прийти ще раз.",
    fa: "هنگام رفتن، پیشخدمت می‌پرسد آیا دوست دارند دوباره بیایند.",
    ar: "عند المغادرة يسأل النادل إن كانوا يرغبون في المجيء مرة أخرى.",
    fr: "En partant, le serveur demande s'ils aimeraient revenir.",
    es: "Al irse, el camarero pregunta si les gustaría volver.",
    it: "Quando vanno via, il cameriere chiede se vorrebbero tornare.",
    pl: "Przy wyjściu kelner pyta, czy chcieliby przyjść ponownie.",
  },
  "Meryem has done more housework than Jonas these past few days.": {
    ru: "За последние несколько дней Мерьем сделала больше домашних дел, чем Йонас.",
    uk: "За останні кілька днів Мер’єм зробила більше хатньої роботи, ніж Йонас.",
    fa: "مریم در چند روز گذشته بیشتر از یوناس کارهای خانه را انجام داده است.",
    ar: "قامت مريم في الأيام القليلة الماضية بأعمال منزلية أكثر من يونس.",
    fr: "Ces derniers jours, Meryem a fait plus de tâches ménagères que Jonas.",
    es: "En los últimos días, Meryem ha hecho más tareas de casa que Jonas.",
    it: "Negli ultimi giorni Meryem ha fatto più lavori domestici di Jonas.",
    pl: "W ciągu ostatnich kilku dni Meryem zrobiła więcej prac domowych niż Jonas.",
  },
  "Jonas says that he has been working late in the evenings.": {
    ru: "Йонас говорит, что в последние вечера он работал допоздна.",
    uk: "Йонас каже, що останнім часом він працював допізна вечорами.",
    fa: "یوناس می‌گوید که این روزها عصرها تا دیروقت کار کرده است.",
    ar: "يقول يونس إنه كان يعمل حتى وقت متأخر من المساء.",
    fr: "Jonas dit qu'il a travaillé tard le soir ces derniers temps.",
    es: "Jonas dice que últimamente ha estado trabajando hasta tarde por las noches.",
    it: "Jonas dice che ultimamente ha lavorato fino a tardi la sera.",
    pl: "Jonas mówi, że ostatnio pracował wieczorami do późna.",
  },
  "Meryem's mother is coming to visit on the weekend.": {
    ru: "Мама Мерьем приедет в гости на выходных.",
    uk: "Мама Мер’єм приїде в гості на вихідних.",
    fa: "مادر مریم آخر هفته برای دیدار می‌آید.",
    ar: "ستأتي والدة مريم لزيارتها في عطلة نهاية الأسبوع.",
    fr: "La mère de Meryem vient lui rendre visite ce week-end.",
    es: "La madre de Meryem viene de visita este fin de semana.",
    it: "La madre di Meryem viene a farle visita nel fine settimana.",
    pl: "Mama Meryem przyjeżdża z wizytą w weekend.",
  },
  "Jonas has already invited friends over.": {
    ru: "Йонас уже пригласил друзей домой.",
    uk: "Йонас уже запросив друзів додому.",
    fa: "یوناس قبلاً دوستانش را دعوت کرده است.",
    ar: "كان يونس قد دعا أصدقاءه بالفعل.",
    fr: "Jonas a déjà invité des amis à la maison.",
    es: "Jonas ya ha invitado a unos amigos.",
    it: "Jonas ha già invitato degli amici.",
    pl: "Jonas zaprosił już znajomych do domu.",
  },
  "Jonas likes the idea but needs help reorganizing things.": {
    ru: "Йонасу нравится эта идея, но ему нужна помощь, чтобы всё перестроить.",
    uk: "Йонасу подобається ця ідея, але йому потрібна допомога, щоб усе перебудувати.",
    fa: "یوناس از این ایده خوشش می‌آید، اما برای دوباره مرتب کردن همه‌چیز به کمک نیاز دارد.",
    ar: "تعجب الفكرة يونس، لكنه يحتاج إلى مساعدة لإعادة ترتيب الأمور.",
    fr: "Jonas aime l'idée, mais il a besoin d'aide pour tout réorganiser.",
    es: "A Jonas le gusta la idea, pero necesita ayuda para reorganizarlo todo.",
    it: "A Jonas piace l'idea, ma ha bisogno di aiuto per riorganizzare tutto.",
    pl: "Jonasowi podoba się ten pomysł, ale potrzebuje pomocy w przeorganizowaniu wszystkiego.",
  },
  "At the end, they have a shared plan for chores and guests.": {
    ru: "В конце у них есть общий план по домашним делам и гостям.",
    uk: "У підсумку в них є спільний план щодо хатніх справ і гостей.",
    fa: "در پایان، آن‌ها یک برنامه مشترک برای کارهای خانه و مهمان‌ها دارند.",
    ar: "في النهاية أصبح لديهما خطة مشتركة للأعمال المنزلية والضيوف.",
    fr: "À la fin, ils ont un plan commun pour les tâches et les invités.",
    es: "Al final, tienen un plan compartido para las tareas y los invitados.",
    it: "Alla fine hanno un piano comune per le faccende e gli ospiti.",
    pl: "Na końcu mają wspólny plan dotyczący obowiązków i gości.",
  },
  "Daniel does not understand one seminar task.": {
    ru: "Даниэль не понимает одно задание семинара.",
    uk: "Даніель не розуміє одне завдання на семінарі.",
    fa: "دانیل یکی از تکلیف‌های سمینار را نمی‌فهمد.",
    ar: "لا يفهم دانيال إحدى مهمات الندوة.",
    fr: "Daniel ne comprend pas une tâche du séminaire.",
    es: "Daniel no entiende una tarea del seminario.",
    it: "Daniel non capisce un compito del seminario.",
    pl: "Daniel nie rozumie jednego zadania na seminarium.",
  },
  "The tutor explains the task, but Daniel still needs one example.": {
    ru: "Куратор объясняет задание, но Даниэлю всё ещё нужен один пример.",
    uk: "Викладач пояснює завдання, але Даніелю все одно потрібен ще один приклад.",
    fa: "استاد راهنما تکلیف را توضیح می‌دهد، اما دانیل هنوز به یک مثال نیاز دارد.",
    ar: "يشرح المدرّس المهمة، لكن دانيال ما زال يحتاج إلى مثال واحد.",
    fr: "Le tuteur explique la tâche, mais Daniel a encore besoin d'un exemple.",
    es: "El tutor explica la tarea, pero Daniel todavía necesita un ejemplo.",
    it: "Il tutor spiega il compito, ma Daniel ha ancora bisogno di un esempio.",
    pl: "Prowadzący wyjaśnia zadanie, ale Daniel wciąż potrzebuje jednego przykładu.",
  },
  "Later, Sara and Daniel work on the presentation slides.": {
    ru: "Позже Сара и Даниэль работают над слайдами презентации.",
    uk: "Пізніше Сара й Даніель працюють над слайдами презентації.",
    fa: "بعدتر، سارا و دانیل روی اسلایدهای ارائه کار می‌کنند.",
    ar: "لاحقًا تعمل سارة ودانيال على شرائح العرض التقديمي.",
    fr: "Plus tard, Sara et Daniel travaillent sur les diapositives de la présentation.",
    es: "Más tarde, Sara y Daniel trabajan en las diapositivas de la presentación.",
    it: "Più tardi Sara e Daniel lavorano alle slide della presentazione.",
    pl: "Później Sara i Daniel pracują nad slajdami prezentacji.",
  },
  "Daniel is a bit nervous before the presentation.": {
    ru: "Даниэль немного нервничает перед презентацией.",
    uk: "Даніель трохи нервує перед презентацією.",
    fa: "دانیل قبل از ارائه کمی عصبی است.",
    ar: "يشعر دانيال ببعض التوتر قبل العرض التقديمي.",
    fr: "Daniel est un peu nerveux avant la présentation.",
    es: "Daniel está un poco nervioso antes de la presentación.",
    it: "Daniel è un po' nervoso prima della presentazione.",
    pl: "Daniel jest trochę zdenerwowany przed prezentacją.",
  },
  "After the presentation, the professor asks a difficult question.": {
    ru: "После презентации профессор задаёт сложный вопрос.",
    uk: "Після презентації професор ставить складне запитання.",
    fa: "بعد از ارائه، استاد یک سؤال دشوار می‌پرسد.",
    ar: "بعد العرض يطرح الأستاذ سؤالًا صعبًا.",
    fr: "Après la présentation, le professeur pose une question difficile.",
    es: "Después de la presentación, el profesor hace una pregunta difícil.",
    it: "Dopo la presentazione, il professore fa una domanda difficile.",
    pl: "Po prezentacji profesor zadaje trudne pytanie.",
  },
  "At the end, both feel relieved and talk about the day.": {
    ru: "В конце оба чувствуют облегчение и разговаривают о дне.",
    uk: "Наприкінці обом стає легше, і вони говорять про день.",
    fa: "در پایان، هر دو احساس آرامش می‌کنند و درباره روز صحبت می‌کنند.",
    ar: "في النهاية يشعر كلاهما بالارتياح ويتحدثان عن اليوم.",
    fr: "À la fin, tous les deux se sentent soulagés et parlent de la journée.",
    es: "Al final, ambos se sienten aliviados y hablan del día.",
    it: "Alla fine entrambi si sentono sollevati e parlano della giornata.",
    pl: "Na końcu oboje czują ulgę i rozmawiają o dniu.",
  },
  "Pedro asks whether the connection in Munich is safe.": {
    ru: "Педро спрашивает, успеет ли он на пересадку в Мюнхене.",
    uk: "Педро запитує, чи встигне він на пересадку в Мюнхені.",
    fa: "پدرو می‌پرسد آیا تعویض قطار در مونیخ امن است.",
    ar: "يسأل بيدرو ما إذا كانت وصلة القطار في ميونيخ مضمونة.",
    fr: "Pedro demande si la correspondance à Munich est sûre.",
    es: "Pedro pregunta si la conexión en Múnich es segura.",
    it: "Pedro chiede se la coincidenza a Monaco è sicura.",
    pl: "Pedro pyta, czy przesiadka w Monachium jest pewna.",
  },
  "Soon after that, the app shows a delay of twenty minutes.": {
    ru: "Вскоре после этого приложение показывает задержку в двадцать минут.",
    uk: "Невдовзі після цього застосунок показує затримку на двадцять хвилин.",
    fa: "کمی بعد، برنامه تأخیری بیست دقیقه‌ای را نشان می‌دهد.",
    ar: "بعد ذلك بقليل يُظهر التطبيق تأخيرًا لمدة عشرين دقيقة.",
    fr: "Peu après, l'application affiche un retard de vingt minutes.",
    es: "Poco después, la aplicación muestra un retraso de veinte minutos.",
    it: "Poco dopo, l'app mostra un ritardo di venti minuti.",
    pl: "Niedługo potem aplikacja pokazuje dwadzieścia minut opóźnienia.",
  },
  "Pedro gets nervous and asks what to do if the connection is gone.": {
    ru: "Педро нервничает и спрашивает, что делать, если пересадка сорвётся.",
    uk: "Педро починає нервувати й запитує, що робити, якщо пересадка зірветься.",
    fa: "پدرو مضطرب می‌شود و می‌پرسد اگر اتصال از دست برود چه باید کرد.",
    ar: "يشعر بيدرو بالتوتر ويسأل ماذا يفعل إذا فاتته الوصلة.",
    fr: "Pedro devient nerveux et demande quoi faire si la correspondance est manquée.",
    es: "Pedro se pone nervioso y pregunta qué hacer si pierde la conexión.",
    it: "Pedro si innervosisce e chiede cosa fare se perde la coincidenza.",
    pl: "Pedro denerwuje się i pyta, co zrobić, jeśli przesiadka przepadnie.",
  },
  "The conductor comes by and asks for the tickets.": {
    ru: "Подходит контролёр и просит билеты.",
    uk: "Підходить контролер і просить квитки.",
    fa: "مامور قطار می‌آید و بلیت‌ها را می‌خواهد.",
    ar: "يمرّ المفتش ويطلب التذاكر.",
    fr: "Le contrôleur passe et demande les billets.",
    es: "Pasa el revisor y pide los billetes.",
    it: "Passa il controllore e chiede i biglietti.",
    pl: "Podchodzi konduktor i prosi o bilety.",
  },
  "Eva checks and confirms a later connection.": {
    ru: "Ева проверяет и подтверждает более позднюю пересадку.",
    uk: "Єва перевіряє й підтверджує пізнішу пересадку.",
    fa: "اوا بررسی می‌کند و یک اتصال دیرتر را تأیید می‌کند.",
    ar: "تتحقق إيفا وتؤكد وجود وصلة لاحقة.",
    fr: "Eva vérifie et confirme une correspondance plus tardive.",
    es: "Eva lo comprueba y confirma una conexión más tarde.",
    it: "Eva controlla e conferma una coincidenza più tardi.",
    pl: "Eva sprawdza i potwierdza późniejsze połączenie.",
  },
  "In the end, the train reaches Munich almost on time.": {
    ru: "В итоге поезд прибывает в Мюнхен почти вовремя.",
    uk: "У підсумку потяг прибуває до Мюнхена майже вчасно.",
    fa: "در نهایت، قطار تقریباً به‌موقع به مونیخ می‌رسد.",
    ar: "في النهاية يصل القطار إلى ميونيخ في الوقت تقريبًا.",
    fr: "Au final, le train arrive à Munich presque à l'heure.",
    es: "Al final, el tren llega a Múnich casi a tiempo.",
    it: "Alla fine il treno arriva a Monaco quasi in orario.",
    pl: "Ostatecznie pociąg dociera do Monachium prawie na czas.",
  },
  "After the flight, Nadia's suitcase does not appear on the baggage belt.": {
    ru: "После полёта чемодан Надии не появляется на багажной ленте.",
    uk: "Після перельоту валіза Надії не з’являється на стрічці видачі багажу.",
    fa: "بعد از پرواز، چمدان نادیا روی نوار بار ظاهر نمی‌شود.",
    ar: "بعد الرحلة لا تظهر حقيبة ناديا على سير الأمتعة.",
    fr: "Après le vol, la valise de Nadia n'apparaît pas sur le tapis à bagages.",
    es: "Después del vuelo, la maleta de Nadia no aparece en la cinta de equipaje.",
    it: "Dopo il volo, la valigia di Nadia non compare sul nastro bagagli.",
    pl: "Po locie walizka Nadii nie pojawia się na taśmie bagażowej.",
  },
  "Later at the hotel, Tom says the booked room is not ready yet.": {
    ru: "Позже в отеле Том говорит, что забронированный номер ещё не готов.",
    uk: "Пізніше в готелі Том каже, що заброньований номер ще не готовий.",
    fa: "بعدتر در هتل، تام می‌گوید اتاق رزرو شده هنوز آماده نیست.",
    ar: "لاحقًا في الفندق يقول توم إن الغرفة المحجوزة ليست جاهزة بعد.",
    fr: "Plus tard à l'hôtel, Tom dit que la chambre réservée n'est pas encore prête.",
    es: "Más tarde, en el hotel, Tom dice que la habitación reservada todavía no está lista.",
    it: "Più tardi in hotel, Tom dice che la camera prenotata non è ancora pronta.",
    pl: "Później w hotelu Tom mówi, że zarezerwowany pokój nie jest jeszcze gotowy.",
  },
  "Karim still wants to visit a museum that same evening.": {
    ru: "Карим всё ещё хочет посетить музей в тот же вечер.",
    uk: "Карім усе ще хоче відвідати музей того ж вечора.",
    fa: "کریم هنوز می‌خواهد همان شب از یک موزه دیدن کند.",
    ar: "ما زال كريم يريد زيارة متحف في المساء نفسه.",
    fr: "Karim veut quand même visiter un musée ce soir-là.",
    es: "Karim todavía quiere visitar un museo esa misma tarde.",
    it: "Karim vuole comunque visitare un museo quella stessa sera.",
    pl: "Karim nadal chce odwiedzić muzeum tego samego wieczoru.",
  },
  "The next morning it rains heavily and the planned city walk is cancelled.": {
    ru: "На следующее утро идёт сильный дождь, и запланированную прогулку по городу отменяют.",
    uk: "Наступного ранку йде сильний дощ, і заплановану прогулянку містом скасовують.",
    fa: "صبح روز بعد باران شدیدی می‌بارد و پیاده‌روی برنامه‌ریزی‌شده در شهر لغو می‌شود.",
    ar: "في صباح اليوم التالي يهطل المطر بغزارة وتُلغى جولة المدينة المخططة.",
    fr: "Le lendemain matin, il pleut fortement et la promenade en ville prévue est annulée.",
    es: "A la mañana siguiente llueve mucho y se cancela el paseo por la ciudad planeado.",
    it: "La mattina seguente piove forte e la passeggiata in città prevista viene annullata.",
    pl: "Następnego ranka mocno pada i zaplanowany spacer po mieście zostaje odwołany.",
  },
  "Later the airline calls and says Nadia's suitcase has arrived.": {
    ru: "Позже авиакомпания звонит и сообщает, что чемодан Надии прибыл.",
    uk: "Пізніше авіакомпанія телефонує й каже, що валіза Надії прибула.",
    fa: "بعدتر شرکت هواپیمایی تماس می‌گیرد و می‌گوید چمدان نادیا رسیده است.",
    ar: "لاحقًا تتصل شركة الطيران وتقول إن حقيبة ناديا قد وصلت.",
    fr: "Plus tard, la compagnie aérienne appelle et dit que la valise de Nadia est arrivée.",
    es: "Más tarde la aerolínea llama y dice que la maleta de Nadia ha llegado.",
    it: "Più tardi la compagnia aerea chiama e dice che la valigia di Nadia è arrivata.",
    pl: "Później linia lotnicza dzwoni i mówi, że walizka Nadii dotarła.",
  },
  "In the evening, Nadia and Karim talk about the trip so far.": {
    ru: "Вечером Надия и Карим разговаривают о поездке до сих пор.",
    uk: "Увечері Надія й Карім говорять про подорож до цього моменту.",
    fa: "عصر، نادیا و کریم درباره سفر تا اینجا صحبت می‌کنند.",
    ar: "في المساء تتحدث ناديا وكريم عن الرحلة حتى الآن.",
    fr: "Le soir, Nadia et Karim parlent du voyage jusqu'à présent.",
    es: "Por la noche, Nadia y Karim hablan del viaje hasta ahora.",
    it: "La sera Nadia e Karim parlano del viaggio fino a quel momento.",
    pl: "Wieczorem Nadia i Karim rozmawiają o dotychczasowej podróży.",
  },
  "Hi! Are you coming to the language cafe today?": {
    fa: "سلام! امروز به کافه زبان می‌آیی؟",
    ar: "مرحبًا! هل ستأتي إلى مقهى اللغات اليوم؟",
  },
  "What is your name?": {
    fa: "اسم تو چیست؟",
    ar: "ما اسمك؟",
  },
  "When does the course start?": {
    fa: "دوره چه زمانی شروع می‌شود؟",
    ar: "متى تبدأ الدورة؟",
  },
  "Can you help me with this word?": {
    fa: "می‌توانی در مورد این کلمه به من کمک کنی؟",
    ar: "هل يمكنك أن تساعدني في هذه الكلمة؟",
  },
  "Where are you right now?": {
    fa: "الان کجا هستی؟",
    ar: "أين أنت الآن؟",
  },
  "Would you like coffee or tea?": {
    fa: "قهوه می‌خواهی یا چای؟",
    ar: "هل تود قهوة أم شايًا؟",
  },
  "Are you in class today?": {
    fa: "امروز در کلاس هستی؟",
    ar: "هل أنت في الصف اليوم؟",
  },
  "Shall we meet at the station?": {
    fa: "در ایستگاه همدیگر را ببینیم؟",
    ar: "هل نلتقي في المحطة؟",
  },
  "Is this seat free?": {
    fa: "این صندلی خالی است؟",
    ar: "هل هذا المقعد شاغر؟",
  },
  "Do you speak German or English?": {
    fa: "آلمانی صحبت می‌کنی یا انگلیسی؟",
    ar: "هل تتحدث الألمانية أم الإنجليزية؟",
  },
  "Did you find the classroom?": {
    fa: "کلاس را پیدا کردی؟",
    ar: "هل وجدت قاعة الدرس؟",
  },
  "Can you send me the address?": {
    fa: "می‌توانی آدرس را برایم بفرستی؟",
    ar: "هل يمكنك أن ترسل لي العنوان؟",
  },
  "I am ten minutes late. Is that okay?": {
    fa: "من ده دقیقه دیر می‌رسم. اشکالی ندارد؟",
    ar: "سأتأخر عشر دقائق. هل هذا مناسب؟",
  },
  "Can you bring your notebook, please?": {
    fa: "می‌شود دفترت را هم بیاوری؟",
    ar: "هل يمكنك أن تحضر دفترك، من فضلك؟",
  },
  "Do you still have time after work?": {
    fa: "بعد از کار هنوز وقت داری؟",
    ar: "هل لا يزال لديك وقت بعد العمل؟",
  },
  "Can you reserve two seats?": {
    fa: "می‌توانی دو جا رزرو کنی؟",
    ar: "هل يمكنك حجز مقعدين؟",
  },
  "Do you know when the train arrives?": {
    fa: "می‌دانی قطار چه وقت می‌رسد؟",
    ar: "هل تعرف متى يصل القطار؟",
  },
  "Can you explain the homework to me?": {
    fa: "می‌توانی تکلیف را برایم توضیح بدهی؟",
    ar: "هل يمكنك أن تشرح لي الواجب؟",
  },
  "We meet on Thursday instead of Wednesday now.": {
    fa: "حالا به‌جای چهارشنبه، پنجشنبه همدیگر را می‌بینیم.",
    ar: "سنلتقي الآن يوم الخميس بدلًا من الأربعاء.",
  },
  "Would you like to join our study group?": {
    fa: "دوست داری به گروه مطالعه ما بپیوندی؟",
    ar: "هل تود الانضمام إلى مجموعة الدراسة الخاصة بنا؟",
  },
  "Please call me when you are there.": {
    fa: "لطفاً وقتی رسیدی به من زنگ بزن.",
    ar: "من فضلك اتصل بي عندما تصل إلى هناك.",
  },
  "Have you bought the tickets already?": {
    fa: "آیا بلیت‌ها را قبلاً خریده‌ای؟",
    ar: "هل اشتريت التذاكر بالفعل؟",
  },
  "Can you quickly take a photo of us?": {
    fa: "می‌توانی سریع از ما یک عکس بگیری؟",
    ar: "هل يمكنك أن تلتقط لنا صورة بسرعة؟",
  },
  "Please do not forget the documents.": {
    fa: "لطفاً مدارک را فراموش نکن.",
    ar: "من فضلك لا تنسَ المستندات.",
  },
  "How did you like today's language evening?": {
    fa: "از برنامه زبانی امروز خوشت آمد؟",
    ar: "كيف وجدت أمسية اللغات اليوم؟",
  },
  "It should rain heavily tomorrow. Should we postpone the meeting?": {
    fa: "فردا احتمالاً باران شدیدی می‌بارد. قرار را عقب بیندازیم؟",
    ar: "من المفترض أن يهطل المطر بغزارة غدًا. هل نؤجل اللقاء؟",
  },
  "How can we practise our German regularly outside class?": {
    fa: "چطور می‌توانیم بیرون از کلاس به‌طور منظم آلمانی تمرین کنیم؟",
    ar: "كيف يمكننا أن نمارس الألمانية بانتظام خارج الصف؟",
  },
  "Can you briefly summarize the most important points?": {
    fa: "می‌توانی مهم‌ترین نکته‌ها را خیلی کوتاه خلاصه کنی؟",
    ar: "هل يمكنك أن تلخص أهم النقاط باختصار؟",
  },
  "Can you help at the event on Saturday?": {
    fa: "می‌توانی شنبه در رویداد کمک کنی؟",
    ar: "هل يمكنك المساعدة في الفعالية يوم السبت؟",
  },
  "I am not sure how we should divide the groups.": {
    fa: "مطمئن نیستم باید گروه‌ها را چطور تقسیم کنیم.",
    ar: "لست متأكدًا كيف ينبغي أن نقسم المجموعات.",
  },
  "What could we improve in the course?": {
    fa: "در این دوره چه چیزی را می‌توانیم بهتر کنیم؟",
    ar: "ما الذي يمكننا تحسينه في الدورة؟",
  },
  "The video loads very slowly for me. Do you have the same problem?": {
    fa: "ویدئو برای من خیلی کند باز می‌شود. تو هم همین مشکل را داری؟",
    ar: "الفيديو يحمّل ببطء شديد عندي. هل لديك المشكلة نفسها؟",
  },
  "Can you prepare the first part if I take over the moderation?": {
    fa: "اگر اداره جلسه را من بر عهده بگیرم، تو می‌توانی بخش اول را آماده کنی؟",
    ar: "هل يمكنك تحضير الجزء الأول إذا توليت أنا إدارة الحوار؟",
  },
  "Will you manage the text today?": {
    fa: "امروز متن را تو مدیریت می‌کنی؟",
    ar: "هل ستتولى النص اليوم؟",
  },
  "Thanks again for your help yesterday.": {
    fa: "باز هم بابت کمکت دیروز ممنونم.",
    ar: "شكرًا مرة أخرى على مساعدتك أمس.",
  },
  "I think we need one more rehearsal.": {
    fa: "فکر می‌کنم به یک تمرین دیگر نیاز داریم.",
    ar: "أعتقد أننا نحتاج إلى بروفة أخرى.",
  },
};
