export type ArticleOption = "der" | "die" | "das";

export type ArticleExercise = {
  id: string;
  noun: string;
  article: ArticleOption;
  hint: string;
  emoji?: string;
  level: "A1" | "A2" | "B1";
};

export type TranslationExercise = {
  id: string;
  source: string;
  target: string;
  emoji: string;
  level: "A1" | "A2" | "B1";
};

type ArticleSeed = readonly [string, ArticleOption, string, string?];
type TranslationSeed = readonly [string, string, string, "A1" | "A2"];

const ARTICLE_EXERCISE_TARGET = 500;
const TRANSLATION_EXERCISE_TARGET = 1000;

const ARTICLE_A1_BASE: ReadonlyArray<ArticleSeed> = [
  ["Apfel", "der", "apple", "🍎"],
  ["Tisch", "der", "table", "🪑"],
  ["Stuhl", "der", "chair", "🪑"],
  ["Bus", "der", "bus", "🚌"],
  ["Zug", "der", "train", "🚆"],
  ["Kaffee", "der", "coffee", "☕"],
  ["Tee", "der", "tea", "🫖"],
  ["Wein", "der", "wine", "🍷"],
  ["Saft", "der", "juice", "🧃"],
  ["Salat", "der", "salad", "🥗"],
  ["Käse", "der", "cheese", "🧀"],
  ["Reis", "der", "rice", "🍚"],
  ["Fisch", "der", "fish", "🐟"],
  ["Zucker", "der", "sugar", "🧂"],
  ["Pfeffer", "der", "pepper", "🧂"],
  ["Kuchen", "der", "cake", "🍰"],
  ["Schinken", "der", "ham", "🥓"],
  ["Löffel", "der", "spoon", "🥄"],
  ["Teller", "der", "plate", "🍽️"],
  ["Herd", "der", "stove", "🍳"],
  ["Kühlschrank", "der", "refrigerator", "🧊"],
  ["Garten", "der", "garden", "🌳"],
  ["Schlüssel", "der", "key", "🔑"],
  ["Computer", "der", "computer", "💻"],
  ["Fernseher", "der", "television", "📺"],
  ["Wecker", "der", "alarm clock", "⏰"],
  ["Besen", "der", "broom", "🧹"],
  ["Eimer", "der", "bucket", "🪣"],
  ["Schalter", "der", "switch", "🎚️"],
  ["Koffer", "der", "suitcase", "🧳"],
  ["Regenschirm", "der", "umbrella", "☂️"],
  ["Bildschirm", "der", "screen", "🖥️"],
  ["Vater", "der", "father", "👨"],
  ["Bruder", "der", "brother", "👦"],
  ["Sohn", "der", "son", "👦"],
  ["Großvater", "der", "grandfather", "👴"],
  ["Mann", "der", "man", "👨"],
  ["Junge", "der", "boy", "🧒"],
  ["Freund", "der", "friend", "🤝"],
  ["Lehrer", "der", "teacher", "👨‍🏫"],
  ["Arzt", "der", "doctor", "👨‍⚕️"],
  ["Koch", "der", "cook", "👨‍🍳"],
  ["Fahrer", "der", "driver", "🚗"],
  ["Verkäufer", "der", "seller", "🛍️"],
  ["Besucher", "der", "visitor", "🚪"],
  ["Nachbar", "der", "neighbor", "🏘️"],
  ["Student", "der", "student", "🎓"],
  ["Kellner", "der", "waiter", "🍽️"],
  ["Polizist", "der", "police officer", "👮"],
  ["Kunde", "der", "customer", "🛒"],
  ["Suppe", "die", "soup", "🍲"],
  ["Banane", "die", "banana", "🍌"],
  ["Orange", "die", "orange", "🍊"],
  ["Kartoffel", "die", "potato", "🥔"],
  ["Tomate", "die", "tomato", "🍅"],
  ["Gurke", "die", "cucumber", "🥒"],
  ["Zitrone", "die", "lemon", "🍋"],
  ["Butter", "die", "butter", "🧈"],
  ["Milch", "die", "milk", "🥛"],
  ["Marmelade", "die", "jam", "🍯"],
  ["Pizza", "die", "pizza", "🍕"],
  ["Wurst", "die", "sausage", "🌭"],
  ["Gabel", "die", "fork", "🍴"],
  ["Pfanne", "die", "pan", "🍳"],
  ["Tasse", "die", "cup", "☕"],
  ["Flasche", "die", "bottle", "🍾"],
  ["Dose", "die", "can", "🥫"],
  ["Küche", "die", "kitchen", "🍽️"],
  ["Mahlzeit", "die", "meal", "🥘"],
  ["Bohne", "die", "bean", "🫘"],
  ["Lampe", "die", "lamp", "💡"],
  ["Tür", "die", "door", "🚪"],
  ["Wand", "die", "wall", "🧱"],
  ["Decke", "die", "ceiling", "🏠"],
  ["Treppe", "die", "stairs", "🪜"],
  ["Wohnung", "die", "apartment", "🏢"],
  ["Garage", "die", "garage", "🚗"],
  ["Schublade", "die", "drawer", "🗄️"],
  ["Seife", "die", "soap", "🧼"],
  ["Bürste", "die", "brush", "🪥"],
  ["Dusche", "die", "shower", "🚿"],
  ["Badewanne", "die", "bathtub", "🛁"],
  ["Klingel", "die", "doorbell", "🔔"],
  ["Matratze", "die", "mattress", "🛏️"],
  ["Uhr", "die", "clock", "🕒"],
  ["Steckdose", "die", "socket", "🔌"],
  ["Fernbedienung", "die", "remote control", "🎮"],
  ["Waschmaschine", "die", "washing machine", "🧺"],
  ["Mutter", "die", "mother", "👩"],
  ["Schwester", "die", "sister", "👧"],
  ["Tochter", "die", "daughter", "👧"],
  ["Großmutter", "die", "grandmother", "👵"],
  ["Frau", "die", "woman", "👩"],
  ["Freundin", "die", "female friend", "💁"],
  ["Lehrerin", "die", "female teacher", "👩‍🏫"],
  ["Ärztin", "die", "female doctor", "👩‍⚕️"],
  ["Verkäuferin", "die", "saleswoman", "🛍️"],
  ["Nachbarin", "die", "female neighbor", "🏘️"],
  ["Studentin", "die", "female student", "🎓"],
  ["Polizistin", "die", "female police officer", "👮‍♀️"],
  ["Brot", "das", "bread", "🍞"],
  ["Wasser", "das", "water", "💧"],
  ["Ei", "das", "egg", "🥚"],
  ["Salz", "das", "salt", "🧂"],
  ["Öl", "das", "oil", "🫒"],
  ["Gemüse", "das", "vegetables", "🥦"],
  ["Fleisch", "das", "meat", "🥩"],
  ["Brötchen", "das", "bread roll", "🥯"],
  ["Sandwich", "das", "sandwich", "🥪"],
  ["Frühstück", "das", "breakfast", "🍳"],
  ["Mittagessen", "das", "lunch", "🍛"],
  ["Abendessen", "das", "dinner", "🍽️"],
  ["Messer", "das", "knife", "🔪"],
  ["Glas", "das", "glass", "🥛"],
  ["Rezept", "das", "recipe", "📝"],
  ["Menü", "das", "menu", "📋"],
  ["Eis", "das", "ice cream", "🍨"],
  ["Müsli", "das", "muesli", "🥣"],
  ["Haus", "das", "house", "🏠"],
  ["Zimmer", "das", "room", "🛋️"],
  ["Fenster", "das", "window", "🪟"],
  ["Bett", "das", "bed", "🛏️"],
  ["Sofa", "das", "sofa", "🛋️"],
  ["Regal", "das", "shelf", "🗄️"],
  ["Handy", "das", "mobile phone", "📱"],
  ["Radio", "das", "radio", "📻"],
  ["Tablet", "das", "tablet", "📲"],
  ["Licht", "das", "light", "💡"],
  ["Bad", "das", "bathroom", "🛁"],
  ["Wohnzimmer", "das", "living room", "🛋️"],
  ["Schlafzimmer", "das", "bedroom", "🛏️"],
  ["Kissen", "das", "pillow", "🛏️"],
  ["Handtuch", "das", "towel", "🧻"],
  ["Dach", "das", "roof", "🏠"],
  ["Schloss", "das", "lock", "🔒"],
  ["Werkzeug", "das", "tool", "🛠️"],
  ["Spielzeug", "das", "toy", "🧸"],
  ["Waschbecken", "das", "sink", "🚰"],
  ["Kabel", "das", "cable", "🔌"],
  ["Foto", "das", "photo", "📷"],
  ["Bild", "das", "picture", "🖼️"],
  ["Poster", "das", "poster", "🖼️"],
  ["Paket", "das", "package", "📦"],
  ["Geschenk", "das", "gift", "🎁"],
  ["Kind", "das", "child", "🧒"],
  ["Baby", "das", "baby", "👶"],
  ["Auge", "das", "eye", "👁️"],
  ["Ohr", "das", "ear", "👂"],
  ["Gesicht", "das", "face", "🙂"],
  ["Bein", "das", "leg", "🦵"],
];

function slugifyWord(value: string): string {
  return value
    .toLowerCase()
    .replace(/ä/g, "ae")
    .replace(/ö/g, "oe")
    .replace(/ü/g, "ue")
    .replace(/ß/g, "ss")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function buildArticleExercises(): ArticleExercise[] {
  return Array.from({ length: ARTICLE_EXERCISE_TARGET }, (_, index) => {
    const seed = ARTICLE_A1_BASE[index % ARTICLE_A1_BASE.length];
    const [noun, article, hint, emoji] = seed;
    const variant = Math.floor(index / ARTICLE_A1_BASE.length) + 1;
    return {
      id: `artikel-${slugifyWord(noun)}-${variant}`,
      noun,
      article,
      hint,
      emoji,
      level: "A1",
    };
  });
}

export const ARTICLE_EXERCISES: ArticleExercise[] = buildArticleExercises();

const TRANSLATION_GENERAL_BASE: ReadonlyArray<TranslationSeed> = [
  ["gehen", "go", "🚶", "A1"],
  ["kommen", "come", "➡️", "A1"],
  ["machen", "do", "🛠️", "A1"],
  ["haben", "have", "🧩", "A1"],
  ["sein", "be", "✨", "A1"],
  ["wohnen", "live", "🏘️", "A1"],
  ["lernen", "learn", "📚", "A1"],
  ["sprechen", "speak", "🗣️", "A1"],
  ["hören", "hear", "👂", "A1"],
  ["sehen", "see", "👀", "A1"],
  ["lesen", "read", "📖", "A1"],
  ["schreiben", "write", "✍️", "A1"],
  ["trinken", "drink", "🥤", "A1"],
  ["essen", "eat", "🍽️", "A1"],
  ["kochen", "cook", "👨‍🍳", "A1"],
  ["kaufen", "buy", "🛒", "A1"],
  ["bezahlen", "pay", "💶", "A1"],
  ["arbeiten", "work", "💼", "A1"],
  ["spielen", "play", "⚽", "A1"],
  ["fragen", "ask", "❓", "A1"],
  ["antworten", "answer", "💬", "A1"],
  ["warten", "wait", "⏳", "A1"],
  ["öffnen", "open", "🚪", "A1"],
  ["schließen", "close", "🔒", "A1"],
  ["beginnen", "begin", "🏁", "A1"],
  ["enden", "end", "🛑", "A1"],
  ["fahren", "drive", "🚗", "A1"],
  ["fliegen", "fly", "✈️", "A1"],
  ["schlafen", "sleep", "😴", "A1"],
  ["aufstehen", "get up", "🌅", "A1"],
  ["helfen", "help", "🤝", "A1"],
  ["finden", "find", "🔎", "A1"],
  ["zeigen", "show", "👉", "A1"],
  ["bringen", "bring", "📦", "A2"],
  ["mitnehmen", "take along", "🧳", "A2"],
  ["erklären", "explain", "🧠", "A2"],
  ["vergessen", "forget", "🤔", "A2"],
  ["erinnern", "remember", "📝", "A2"],
  ["besuchen", "visit", "🏠", "A2"],
  ["anmachen", "turn on", "💡", "A2"],
  ["ausmachen", "turn off", "🔌", "A2"],
  ["sauber", "clean", "🧼", "A1"],
  ["schmutzig", "dirty", "🧹", "A1"],
  ["schnell", "fast", "⚡", "A1"],
  ["langsam", "slow", "🐢", "A1"],
  ["groß", "big", "📏", "A1"],
  ["klein", "small", "🔹", "A1"],
  ["neu", "new", "🆕", "A1"],
  ["alt", "old", "🕰️", "A1"],
  ["jung", "young", "🌱", "A1"],
  ["teuer", "expensive", "💎", "A1"],
  ["billig", "cheap", "🪙", "A1"],
  ["schön", "beautiful", "🌸", "A1"],
  ["hässlich", "ugly", "🙈", "A2"],
  ["leicht", "easy", "🪶", "A1"],
  ["schwer", "difficult", "🏋️", "A1"],
  ["hungrig", "hungry", "🍽️", "A1"],
  ["durstig", "thirsty", "🥤", "A1"],
  ["krank", "sick", "🤒", "A1"],
  ["gesund", "healthy", "💚", "A1"],
  ["wichtig", "important", "⭐", "A2"],
  ["fertig", "finished", "✅", "A2"],
  ["leer", "empty", "🫙", "A1"],
  ["voll", "full", "🧺", "A1"],
  ["heute", "today", "📅", "A1"],
  ["morgen", "tomorrow", "🌤️", "A1"],
  ["gestern", "yesterday", "🗓️", "A1"],
  ["immer", "always", "♾️", "A1"],
  ["nie", "never", "🚫", "A1"],
  ["oft", "often", "🔁", "A1"],
  ["manchmal", "sometimes", "🔄", "A1"],
  ["später", "later", "⌛", "A1"],
  ["früh", "early", "🌄", "A1"],
  ["direkt", "directly", "🎯", "A2"],
  ["vielleicht", "maybe", "🤷", "A1"],
  ["wirklich", "really", "💯", "A1"],
  ["zusammen", "together", "🫶", "A1"],
  ["allein", "alone", "🧍", "A1"],
  ["drinnen", "inside", "🏠", "A1"],
  ["draußen", "outside", "🌳", "A1"],
  ["links", "left", "⬅️", "A1"],
  ["rechts", "right", "➡️", "A1"],
  ["oben", "up", "⬆️", "A1"],
  ["unten", "down", "⬇️", "A1"],
  ["Frühling", "spring", "🌷", "A1"],
  ["Herbst", "autumn", "🍂", "A1"],
  ["Winter", "winter", "❄️", "A1"],
  ["Wetter", "weather", "🌦️", "A1"],
  ["Regen", "rain", "🌧️", "A1"],
  ["Schnee", "snow", "🌨️", "A1"],
  ["Wind", "wind", "💨", "A1"],
  ["Wolke", "cloud", "☁️", "A1"],
  ["Sonne", "sun", "☀️", "A1"],
  ["Berg", "mountain", "⛰️", "A1"],
  ["Meer", "sea", "🌊", "A1"],
  ["Fluss", "river", "🏞️", "A2"],
  ["Baum", "tree", "🌳", "A1"],
  ["Blume", "flower", "🌼", "A1"],
  ["Straße", "street", "🛣️", "A1"],
  ["Platz", "square", "📍", "A2"],
  ["Bahnhof", "station", "🚉", "A1"],
  ["Flughafen", "airport", "🛫", "A2"],
  ["Hotel", "hotel", "🏨", "A1"],
  ["Zimmernummer", "room number", "🔢", "A2"],
  ["Ausweis", "identity card", "🪪", "A2"],
  ["Ticketkontrolle", "ticket inspection", "🎫", "A2"],
  ["Fahrrad", "bicycle", "🚲", "A1"],
  ["Auto", "car", "🚗", "A1"],
  ["Taxi", "taxi", "🚕", "A1"],
  ["Ampel", "traffic light", "🚦", "A2"],
  ["Karte", "map", "🗺️", "A1"],
  ["Plan", "plan", "🗓️", "A2"],
  ["Termin", "appointment", "📌", "A2"],
  ["Geburtstag", "birthday", "🎂", "A1"],
  ["Feier", "party", "🥳", "A1"],
  ["Musik", "music", "🎵", "A1"],
  ["Lied", "song", "🎶", "A1"],
  ["Film", "movie", "🎬", "A1"],
  ["Büro", "office", "🏢", "A1"],
  ["Firma", "company", "🏭", "A2"],
  ["Kollege", "colleague", "👥", "A2"],
  ["Pause", "break", "☕", "A2"],
  ["Urlaub", "vacation", "🏖️", "A2"],
  ["Aufgabe", "task", "📋", "A2"],
  ["Prüfung", "exam", "📝", "A2"],
  ["Übung", "exercise", "🏋️", "A2"],
  ["Antwort", "answer", "💬", "A1"],
  ["Fragebogen", "questionnaire", "📄", "A2"],
  ["Farbe", "color", "🎨", "A1"],
  ["rot", "red", "🔴", "A1"],
  ["blau", "blue", "🔵", "A1"],
  ["grün", "green", "🟢", "A1"],
  ["gelb", "yellow", "🟡", "A1"],
  ["schwarz", "black", "⚫", "A1"],
  ["weiß", "white", "⚪", "A1"],
  ["braun", "brown", "🟤", "A1"],
  ["grau", "gray", "◻️", "A1"],
  ["rosa", "pink", "🩷", "A1"],
  ["glücklich", "happy", "😊", "A1"],
  ["traurig", "sad", "😢", "A1"],
  ["müde", "tired", "🥱", "A1"],
  ["nervös", "nervous", "😬", "A2"],
  ["ruhig", "calm", "🧘", "A2"],
  ["laut", "loud", "📣", "A1"],
  ["leise", "quiet", "🤫", "A1"],
  ["klar", "clear", "🔍", "A2"],
  ["bald", "soon", "🕐", "A2"],
];

function buildTranslationExercises(): TranslationExercise[] {
  const base: TranslationSeed[] = [
    ...ARTICLE_A1_BASE.map(([noun, , hint, emoji]) => [
      noun,
      hint,
      emoji ?? "📝",
      "A1",
    ] as const),
    ...TRANSLATION_GENERAL_BASE,
  ];

  return Array.from({ length: TRANSLATION_EXERCISE_TARGET }, (_, index) => {
    const seed = base[index % base.length];
    const [source, target, emoji, level] = seed;
    const variant = Math.floor(index / base.length) + 1;
    return {
      id: `wort-${slugifyWord(source)}-${variant}`,
      source,
      target,
      emoji,
      level,
    };
  });
}

export const TRANSLATION_EXERCISES: TranslationExercise[] = buildTranslationExercises();
