type MiniGamesGlossaryLocale =
  | "en"
  | "de"
  | "vi"
  | "ru"
  | "uk"
  | "fa"
  | "ar"
  | "sq"
  | "tr"
  | "fr"
  | "es"
  | "it"
  | "pl";

type GlossaryEntry = Partial<Record<MiniGamesGlossaryLocale, string>>;

const LOCALE_SET = new Set<MiniGamesGlossaryLocale>([
  "en",
  "de",
  "vi",
  "ru",
  "uk",
  "fa",
  "ar",
  "sq",
  "tr",
  "fr",
  "es",
  "it",
  "pl",
]);

const MINI_GAMES_GLOSSARY: Record<string, GlossaryEntry> = {
  apple: { vi: "táo", ru: "яблоко", uk: "яблуко", fa: "سیب", ar: "تفاحة", sq: "mollë", tr: "elma", fr: "pomme", es: "manzana", it: "mela", pl: "jabłko" },
  table: { vi: "bàn", ru: "стол", uk: "стіл", fa: "میز", ar: "طاولة", sq: "tavolinë", tr: "masa", fr: "table", es: "mesa", it: "tavolo", pl: "stół" },
  chair: { vi: "ghế", ru: "стул", uk: "стілець", fa: "صندلی", ar: "كرسي", sq: "karrige", tr: "sandalye", fr: "chaise", es: "silla", it: "sedia", pl: "krzesło" },
  bus: { vi: "xe buýt", ru: "автобус", uk: "автобус", fa: "اتوبوس", ar: "حافلة", sq: "autobus", tr: "otobüs", fr: "bus", es: "autobús", it: "autobus", pl: "autobus" },
  train: { vi: "tàu hỏa", ru: "поезд", uk: "поїзд", fa: "قطار", ar: "قطار", sq: "tren", tr: "tren", fr: "train", es: "tren", it: "treno", pl: "pociąg" },
  coffee: { vi: "cà phê", ru: "кофе", uk: "кава", fa: "قهوه", ar: "قهوة", sq: "kafe", tr: "kahve", fr: "café", es: "café", it: "caffè", pl: "kawa" },
  tea: { vi: "trà", ru: "чай", uk: "чай", fa: "چای", ar: "شاي", sq: "çaj", tr: "çay", fr: "thé", es: "té", it: "tè", pl: "herbata" },
  wine: { vi: "rượu vang", ru: "вино", uk: "вино", fa: "شراب", ar: "نبيذ", sq: "verë", tr: "şarap", fr: "vin", es: "vino", it: "vino", pl: "wino" },
  juice: { vi: "nước ép", ru: "сок", uk: "сік", fa: "آبمیوه", ar: "عصير", sq: "lëng", tr: "meyve suyu", fr: "jus", es: "zumo", it: "succo", pl: "sok" },
  salad: { vi: "salad", ru: "салат", uk: "салат", fa: "سالاد", ar: "سلطة", sq: "sallatë", tr: "salata", fr: "salade", es: "ensalada", it: "insalata", pl: "sałatka" },
  cheese: { vi: "phô mai", ru: "сыр", uk: "сир", fa: "پنیر", ar: "جبن", sq: "djathë", tr: "peynir", fr: "fromage", es: "queso", it: "formaggio", pl: "ser" },
  rice: { vi: "cơm", ru: "рис", uk: "рис", fa: "برنج", ar: "أرز", sq: "oriz", tr: "pirinç", fr: "riz", es: "arroz", it: "riso", pl: "ryż" },
  fish: { vi: "cá", ru: "рыба", uk: "риба", fa: "ماهی", ar: "سمك", sq: "peshk", tr: "balık", fr: "poisson", es: "pescado", it: "pesce", pl: "ryba" },
  sugar: { vi: "đường", ru: "сахар", uk: "цукор", fa: "شکر", ar: "سكر", sq: "sheqer", tr: "şeker", fr: "sucre", es: "azúcar", it: "zucchero", pl: "cukier" },
  cake: { vi: "bánh ngọt", ru: "торт", uk: "торт", fa: "کیک", ar: "كعكة", sq: "tortë", tr: "pasta", fr: "gâteau", es: "pastel", it: "torta", pl: "ciasto" },
  key: { vi: "chìa khóa", ru: "ключ", uk: "ключ", fa: "کلید", ar: "مفتاح", sq: "çelës", tr: "anahtar", fr: "clé", es: "llave", it: "chiave", pl: "klucz" },
  computer: { vi: "máy tính", ru: "компьютер", uk: "комп’ютер", fa: "کامپیوتر", ar: "حاسوب", sq: "kompjuter", tr: "bilgisayar", fr: "ordinateur", es: "ordenador", it: "computer", pl: "komputer" },
  television: { vi: "ti vi", ru: "телевизор", uk: "телевізор", fa: "تلویزیون", ar: "تلفاز", sq: "televizor", tr: "televizyon", fr: "télévision", es: "televisión", it: "televisione", pl: "telewizor" },
  father: { vi: "bố", ru: "отец", uk: "батько", fa: "پدر", ar: "أب", sq: "babai", tr: "baba", fr: "père", es: "padre", it: "padre", pl: "ojciec" },
  brother: { vi: "anh/em trai", ru: "брат", uk: "брат", fa: "برادر", ar: "أخ", sq: "vëlla", tr: "erkek kardeş", fr: "frère", es: "hermano", it: "fratello", pl: "brat" },
  son: { vi: "con trai", ru: "сын", uk: "син", fa: "پسر", ar: "ابن", sq: "djalë", tr: "oğul", fr: "fils", es: "hijo", it: "figlio", pl: "syn" },
  friend: { vi: "bạn", ru: "друг", uk: "друг", fa: "دوست", ar: "صديق", sq: "mik", tr: "arkadaş", fr: "ami", es: "amigo", it: "amico", pl: "przyjaciel" },
  teacher: { vi: "giáo viên", ru: "учитель", uk: "вчитель", fa: "معلم", ar: "معلّم", sq: "mësues", tr: "öğretmen", fr: "professeur", es: "profesor", it: "insegnante", pl: "nauczyciel" },
  doctor: { vi: "bác sĩ", ru: "врач", uk: "лікар", fa: "پزشک", ar: "طبيب", sq: "mjek", tr: "doktor", fr: "médecin", es: "médico", it: "medico", pl: "lekarz" },
  student: { vi: "sinh viên", ru: "студент", uk: "студент", fa: "دانشجو", ar: "طالب", sq: "student", tr: "öğrenci", fr: "étudiant", es: "estudiante", it: "studente", pl: "student" },
  soup: { vi: "súp", ru: "суп", uk: "суп", fa: "سوپ", ar: "حساء", sq: "supë", tr: "çorba", fr: "soupe", es: "sopa", it: "zuppa", pl: "zupa" },
  banana: { vi: "chuối", ru: "банан", uk: "банан", fa: "موز", ar: "موز", sq: "banane", tr: "muz", fr: "banane", es: "plátano", it: "banana", pl: "banan" },
  orange: { vi: "cam", ru: "апельсин", uk: "апельсин", fa: "پرتقال", ar: "برتقال", sq: "portokall", tr: "portakal", fr: "orange", es: "naranja", it: "arancia", pl: "pomarańcza" },
  potato: { vi: "khoai tây", ru: "картофель", uk: "картопля", fa: "سیب‌زمینی", ar: "بطاطس", sq: "patate", tr: "patates", fr: "pomme de terre", es: "patata", it: "patata", pl: "ziemniak" },
  tomato: { vi: "cà chua", ru: "помидор", uk: "помідор", fa: "گوجه‌فرنگی", ar: "طماطم", sq: "domate", tr: "domates", fr: "tomate", es: "tomate", it: "pomodoro", pl: "pomidor" },
  milk: { vi: "sữa", ru: "молоко", uk: "молоко", fa: "شیر", ar: "حليب", sq: "qumësht", tr: "süt", fr: "lait", es: "leche", it: "latte", pl: "mleko" },
  pizza: { vi: "pizza", ru: "пицца", uk: "піца", fa: "پیتزا", ar: "بيتزا", sq: "picë", tr: "pizza", fr: "pizza", es: "pizza", it: "pizza", pl: "pizza" },
  bottle: { vi: "chai", ru: "бутылка", uk: "пляшка", fa: "بطری", ar: "زجاجة", sq: "shishe", tr: "şişe", fr: "bouteille", es: "botella", it: "bottiglia", pl: "butelka" },
  kitchen: { vi: "bếp", ru: "кухня", uk: "кухня", fa: "آشپزخانه", ar: "مطبخ", sq: "kuzhinë", tr: "mutfak", fr: "cuisine", es: "cocina", it: "cucina", pl: "kuchnia" },
  lamp: { vi: "đèn", ru: "лампа", uk: "лампа", fa: "چراغ", ar: "مصباح", sq: "llampë", tr: "lamba", fr: "lampe", es: "lámpara", it: "lampada", pl: "lampa" },
  door: { vi: "cửa", ru: "дверь", uk: "двері", fa: "در", ar: "باب", sq: "derë", tr: "kapı", fr: "porte", es: "puerta", it: "porta", pl: "drzwi" },
  apartment: { vi: "căn hộ", ru: "квартира", uk: "квартира", fa: "آپارتمان", ar: "شقة", sq: "apartament", tr: "daire", fr: "appartement", es: "apartamento", it: "appartamento", pl: "mieszkanie" },
  mother: { vi: "mẹ", ru: "мать", uk: "мати", fa: "مادر", ar: "أم", sq: "nënë", tr: "anne", fr: "mère", es: "madre", it: "madre", pl: "matka" },
  sister: { vi: "chị/em gái", ru: "сестра", uk: "сестра", fa: "خواهر", ar: "أخت", sq: "motër", tr: "kız kardeş", fr: "sœur", es: "hermana", it: "sorella", pl: "siostra" },
  woman: { vi: "phụ nữ", ru: "женщина", uk: "жінка", fa: "زن", ar: "امرأة", sq: "grua", tr: "kadın", fr: "femme", es: "mujer", it: "donna", pl: "kobieta" },
  bread: { vi: "bánh mì", ru: "хлеб", uk: "хліб", fa: "نان", ar: "خبز", sq: "bukë", tr: "ekmek", fr: "pain", es: "pan", it: "pane", pl: "chleb" },
  water: { vi: "nước", ru: "вода", uk: "вода", fa: "آب", ar: "ماء", sq: "ujë", tr: "su", fr: "eau", es: "agua", it: "acqua", pl: "woda" },
  egg: { vi: "trứng", ru: "яйцо", uk: "яйце", fa: "تخم‌مرغ", ar: "بيضة", sq: "vezë", tr: "yumurta", fr: "œuf", es: "huevo", it: "uovo", pl: "jajko" },
  vegetables: { vi: "rau", ru: "овощи", uk: "овочі", fa: "سبزیجات", ar: "خضروات", sq: "perime", tr: "sebzeler", fr: "légumes", es: "verduras", it: "verdure", pl: "warzywa" },
  breakfast: { vi: "bữa sáng", ru: "завтрак", uk: "сніданок", fa: "صبحانه", ar: "فطور", sq: "mëngjes", tr: "kahvaltı", fr: "petit déjeuner", es: "desayuno", it: "colazione", pl: "śniadanie" },
  house: { vi: "nhà", ru: "дом", uk: "будинок", fa: "خانه", ar: "بيت", sq: "shtëpi", tr: "ev", fr: "maison", es: "casa", it: "casa", pl: "dom" },
  room: { vi: "phòng", ru: "комната", uk: "кімната", fa: "اتاق", ar: "غرفة", sq: "dhomë", tr: "oda", fr: "pièce", es: "habitación", it: "stanza", pl: "pokój" },
  window: { vi: "cửa sổ", ru: "окно", uk: "вікно", fa: "پنجره", ar: "نافذة", sq: "dritare", tr: "pencere", fr: "fenêtre", es: "ventana", it: "finestra", pl: "okno" },
  bed: { vi: "giường", ru: "кровать", uk: "ліжко", fa: "تخت", ar: "سرير", sq: "shtrat", tr: "yatak", fr: "lit", es: "cama", it: "letto", pl: "łóżko" },
  "mobile phone": { vi: "điện thoại di động", ru: "мобильный телефон", uk: "мобільний телефон", fa: "تلفن همراه", ar: "هاتف محمول", sq: "telefon celular", tr: "cep telefonu", fr: "téléphone portable", es: "teléfono móvil", it: "telefono cellulare", pl: "telefon komórkowy" },
  child: { vi: "đứa trẻ", ru: "ребёнок", uk: "дитина", fa: "کودک", ar: "طفل", sq: "fëmijë", tr: "çocuk", fr: "enfant", es: "niño", it: "bambino", pl: "dziecko" },
  baby: { vi: "em bé", ru: "младенец", uk: "немовля", fa: "نوزاد", ar: "رضيع", sq: "foshnjë", tr: "bebek", fr: "bébé", es: "bebé", it: "neonato", pl: "niemowlę" },
  eye: { vi: "mắt", ru: "глаз", uk: "око", fa: "چشم", ar: "عين", sq: "sy", tr: "göz", fr: "œil", es: "ojo", it: "occhio", pl: "oko" },
  face: { vi: "khuôn mặt", ru: "лицо", uk: "обличчя", fa: "صورت", ar: "وجه", sq: "fytyrë", tr: "yüz", fr: "visage", es: "cara", it: "viso", pl: "twarz" },
  go: { vi: "đi", ru: "идти", uk: "йти", fa: "رفتن", ar: "يذهب", sq: "shkoj", tr: "gitmek", fr: "aller", es: "ir", it: "andare", pl: "iść" },
  come: { vi: "đến", ru: "приходить", uk: "приходити", fa: "آمدن", ar: "يأتي", sq: "vij", tr: "gelmek", fr: "venir", es: "venir", it: "venire", pl: "przyjść" },
  do: { vi: "làm", ru: "делать", uk: "робити", fa: "انجام دادن", ar: "يفعل", sq: "bëj", tr: "yapmak", fr: "faire", es: "hacer", it: "fare", pl: "robić" },
  have: { vi: "có", ru: "иметь", uk: "мати", fa: "داشتن", ar: "يملك", sq: "kam", tr: "sahip olmak", fr: "avoir", es: "tener", it: "avere", pl: "mieć" },
  be: { vi: "là", ru: "быть", uk: "бути", fa: "بودن", ar: "يكون", sq: "jam", tr: "olmak", fr: "être", es: "ser", it: "essere", pl: "być" },
  live: { vi: "sống", ru: "жить", uk: "жити", fa: "زندگی کردن", ar: "يعيش", sq: "jetoj", tr: "yaşamak", fr: "vivre", es: "vivir", it: "vivere", pl: "mieszkać" },
  learn: { vi: "học", ru: "учить", uk: "вчити", fa: "یاد گرفتن", ar: "يتعلم", sq: "mësoj", tr: "öğrenmek", fr: "apprendre", es: "aprender", it: "imparare", pl: "uczyć się" },
  speak: { vi: "nói", ru: "говорить", uk: "говорити", fa: "صحبت کردن", ar: "يتحدث", sq: "flas", tr: "konuşmak", fr: "parler", es: "hablar", it: "parlare", pl: "mówić" },
  hear: { vi: "nghe", ru: "слышать", uk: "чути", fa: "شنیدن", ar: "يسمع", sq: "dëgjoj", tr: "duymak", fr: "entendre", es: "oír", it: "sentire", pl: "słyszeć" },
  see: { vi: "nhìn", ru: "видеть", uk: "бачити", fa: "دیدن", ar: "يرى", sq: "shoh", tr: "görmek", fr: "voir", es: "ver", it: "vedere", pl: "widzieć" },
  read: { vi: "đọc", ru: "читать", uk: "читати", fa: "خواندن", ar: "يقرأ", sq: "lexoj", tr: "okumak", fr: "lire", es: "leer", it: "leggere", pl: "czytać" },
  write: { vi: "viết", ru: "писать", uk: "писати", fa: "نوشتن", ar: "يكتب", sq: "shkruaj", tr: "yazmak", fr: "écrire", es: "escribir", it: "scrivere", pl: "pisać" },
  drink: { vi: "uống", ru: "пить", uk: "пити", fa: "نوشیدن", ar: "يشرب", sq: "pi", tr: "içmek", fr: "boire", es: "beber", it: "bere", pl: "pić" },
  eat: { vi: "ăn", ru: "есть", uk: "їсти", fa: "خوردن", ar: "يأكل", sq: "ha", tr: "yemek", fr: "manger", es: "comer", it: "mangiare", pl: "jeść" },
  cook: { vi: "nấu ăn", ru: "готовить", uk: "готувати", fa: "آشپزی کردن", ar: "يطبخ", sq: "gatuaj", tr: "pişirmek", fr: "cuisiner", es: "cocinar", it: "cucinare", pl: "gotować" },
  buy: { vi: "mua", ru: "покупать", uk: "купувати", fa: "خریدن", ar: "يشتري", sq: "blej", tr: "satın almak", fr: "acheter", es: "comprar", it: "comprare", pl: "kupować" },
  pay: { vi: "trả tiền", ru: "платить", uk: "платити", fa: "پرداخت کردن", ar: "يدفع", sq: "paguaj", tr: "ödemek", fr: "payer", es: "pagar", it: "pagare", pl: "płacić" },
  work: { vi: "làm việc", ru: "работать", uk: "працювати", fa: "کار کردن", ar: "يعمل", sq: "punoj", tr: "çalışmak", fr: "travailler", es: "trabajar", it: "lavorare", pl: "pracować" },
  play: { vi: "chơi", ru: "играть", uk: "грати", fa: "بازی کردن", ar: "يلعب", sq: "luaj", tr: "oynamak", fr: "jouer", es: "jugar", it: "giocare", pl: "grać" },
  ask: { vi: "hỏi", ru: "спрашивать", uk: "питати", fa: "پرسیدن", ar: "يسأل", sq: "pyes", tr: "sormak", fr: "demander", es: "preguntar", it: "chiedere", pl: "pytać" },
  answer: { vi: "trả lời", ru: "отвечать", uk: "відповідати", fa: "پاسخ دادن", ar: "يجيب", sq: "përgjigjem", tr: "cevap vermek", fr: "répondre", es: "responder", it: "rispondere", pl: "odpowiadać" },
  wait: { vi: "đợi", ru: "ждать", uk: "чекати", fa: "صبر کردن", ar: "ينتظر", sq: "pres", tr: "beklemek", fr: "attendre", es: "esperar", it: "aspettare", pl: "czekać" },
  open: { vi: "mở", ru: "открывать", uk: "відкривати", fa: "باز کردن", ar: "يفتح", sq: "hap", tr: "açmak", fr: "ouvrir", es: "abrir", it: "aprire", pl: "otwierać" },
  close: { vi: "đóng", ru: "закрывать", uk: "закривати", fa: "بستن", ar: "يغلق", sq: "mbyll", tr: "kapatmak", fr: "fermer", es: "cerrar", it: "chiudere", pl: "zamykać" },
  begin: { vi: "bắt đầu", ru: "начинать", uk: "починати", fa: "شروع کردن", ar: "يبدأ", sq: "filloj", tr: "başlamak", fr: "commencer", es: "empezar", it: "iniziare", pl: "zaczynać" },
  end: { vi: "kết thúc", ru: "заканчивать", uk: "закінчувати", fa: "تمام کردن", ar: "ينهي", sq: "përfundoj", tr: "bitirmek", fr: "finir", es: "terminar", it: "finire", pl: "kończyć" },
  drive: { vi: "lái xe", ru: "вести машину", uk: "кермувати", fa: "رانندگی کردن", ar: "يقود", sq: "ngas", tr: "sürmek", fr: "conduire", es: "conducir", it: "guidare", pl: "prowadzić" },
  sleep: { vi: "ngủ", ru: "спать", uk: "спати", fa: "خوابیدن", ar: "ينام", sq: "fle", tr: "uyumak", fr: "dormir", es: "dormir", it: "dormire", pl: "spać" },
  "get up": { vi: "thức dậy", ru: "вставать", uk: "вставати", fa: "بلند شدن", ar: "يستيقظ", sq: "ngrihem", tr: "kalkmak", fr: "se lever", es: "levantarse", it: "alzarsi", pl: "wstawać" },
  help: { vi: "giúp", ru: "помогать", uk: "допомагати", fa: "کمک کردن", ar: "يساعد", sq: "ndihmoj", tr: "yardım etmek", fr: "aider", es: "ayudar", it: "aiutare", pl: "pomagać" },
  find: { vi: "tìm", ru: "находить", uk: "знаходити", fa: "پیدا کردن", ar: "يجد", sq: "gjej", tr: "bulmak", fr: "trouver", es: "encontrar", it: "trovare", pl: "znaleźć" },
  show: { vi: "chỉ", ru: "показывать", uk: "показувати", fa: "نشان دادن", ar: "يُظهر", sq: "tregoj", tr: "göstermek", fr: "montrer", es: "mostrar", it: "mostrare", pl: "pokazywać" },
  clean: { vi: "sạch", ru: "чистый", uk: "чистий", fa: "تمیز", ar: "نظيف", sq: "i pastër", tr: "temiz", fr: "propre", es: "limpio", it: "pulito", pl: "czysty" },
  dirty: { vi: "bẩn", ru: "грязный", uk: "брудний", fa: "کثیف", ar: "متسخ", sq: "i pistë", tr: "kirli", fr: "sale", es: "sucio", it: "sporco", pl: "brudny" },
  fast: { vi: "nhanh", ru: "быстрый", uk: "швидкий", fa: "سریع", ar: "سريع", sq: "i shpejtë", tr: "hızlı", fr: "rapide", es: "rápido", it: "veloce", pl: "szybki" },
  slow: { vi: "chậm", ru: "медленный", uk: "повільний", fa: "کند", ar: "بطيء", sq: "i ngadaltë", tr: "yavaş", fr: "lent", es: "lento", it: "lento", pl: "wolny" },
  big: { vi: "to", ru: "большой", uk: "великий", fa: "بزرگ", ar: "كبير", sq: "i madh", tr: "büyük", fr: "grand", es: "grande", it: "grande", pl: "duży" },
  small: { vi: "nhỏ", ru: "маленький", uk: "малий", fa: "کوچک", ar: "صغير", sq: "i vogël", tr: "küçük", fr: "petit", es: "pequeño", it: "piccolo", pl: "mały" },
  new: { vi: "mới", ru: "новый", uk: "новий", fa: "جدید", ar: "جديد", sq: "i ri", tr: "yeni", fr: "nouveau", es: "nuevo", it: "nuovo", pl: "nowy" },
  old: { vi: "cũ", ru: "старый", uk: "старий", fa: "قدیمی", ar: "قديم", sq: "i vjetër", tr: "eski", fr: "ancien", es: "viejo", it: "vecchio", pl: "stary" },
  today: { vi: "hôm nay", ru: "сегодня", uk: "сьогодні", fa: "امروز", ar: "اليوم", sq: "sot", tr: "bugün", fr: "aujourd’hui", es: "hoy", it: "oggi", pl: "dzisiaj" },
  tomorrow: { vi: "ngày mai", ru: "завтра", uk: "завтра", fa: "فردا", ar: "غدًا", sq: "nesër", tr: "yarın", fr: "demain", es: "mañana", it: "domani", pl: "jutro" },
  yesterday: { vi: "hôm qua", ru: "вчера", uk: "вчора", fa: "دیروز", ar: "أمس", sq: "dje", tr: "dün", fr: "hier", es: "ayer", it: "ieri", pl: "wczoraj" },
  always: { vi: "luôn luôn", ru: "всегда", uk: "завжди", fa: "همیشه", ar: "دائمًا", sq: "gjithmonë", tr: "her zaman", fr: "toujours", es: "siempre", it: "sempre", pl: "zawsze" },
  never: { vi: "không bao giờ", ru: "никогда", uk: "ніколи", fa: "هرگز", ar: "أبدًا", sq: "kurrë", tr: "asla", fr: "jamais", es: "nunca", it: "mai", pl: "nigdy" },
  together: { vi: "cùng nhau", ru: "вместе", uk: "разом", fa: "باهم", ar: "معًا", sq: "së bashku", tr: "birlikte", fr: "ensemble", es: "juntos", it: "insieme", pl: "razem" },
  alone: { vi: "một mình", ru: "один", uk: "сам", fa: "تنها", ar: "وحده", sq: "vetëm", tr: "yalnız", fr: "seul", es: "solo", it: "da solo", pl: "sam" },
  left: { vi: "bên trái", ru: "слева", uk: "ліворуч", fa: "چپ", ar: "يسار", sq: "majtas", tr: "sol", fr: "gauche", es: "izquierda", it: "sinistra", pl: "lewo" },
  right: { vi: "bên phải", ru: "справа", uk: "праворуч", fa: "راست", ar: "يمين", sq: "djathtas", tr: "sağ", fr: "droite", es: "derecha", it: "destra", pl: "prawo" },
  happy: { vi: "vui", ru: "счастливый", uk: "щасливий", fa: "خوشحال", ar: "سعيد", sq: "i lumtur", tr: "mutlu", fr: "heureux", es: "feliz", it: "felice", pl: "szczęśliwy" },
  sad: { vi: "buồn", ru: "грустный", uk: "сумний", fa: "غمگین", ar: "حزين", sq: "i trishtuar", tr: "üzgün", fr: "triste", es: "triste", it: "triste", pl: "smutny" },
};

const MINI_GAMES_GLOSSARY_EXTRA: Record<string, GlossaryEntry> = {
  airport: { vi: "sân bay", ru: "аэропорт", uk: "аеропорт", fa: "فرودگاه", ar: "مطار", sq: "aeroport", tr: "havaalanı", fr: "aéroport", es: "aeropuerto", it: "aeroporto", pl: "lotnisko" },
  "alarm clock": { vi: "đồng hồ báo thức", ru: "будильник", uk: "будильник", fa: "ساعت زنگ‌دار", ar: "منبه", sq: "orë me alarm", tr: "çalar saat", fr: "réveil", es: "despertador", it: "sveglia", pl: "budzik" },
  appointment: { vi: "cuộc hẹn", ru: "встреча", uk: "зустріч", fa: "قرار ملاقات", ar: "موعد", sq: "takim", tr: "randevu", fr: "rendez-vous", es: "cita", it: "appuntamento", pl: "spotkanie" },
  autumn: { vi: "mùa thu", ru: "осень", uk: "осінь", fa: "پاییز", ar: "خريف", sq: "vjeshtë", tr: "sonbahar", fr: "automne", es: "otoño", it: "autunno", pl: "jesień" },
  bathroom: { vi: "phòng tắm", ru: "ванная", uk: "ванна кімната", fa: "حمام", ar: "حمام", sq: "banjo", tr: "banyo", fr: "salle de bain", es: "baño", it: "bagno", pl: "łazienka" },
  bathtub: { vi: "bồn tắm", ru: "ванна", uk: "ванна", fa: "وان", ar: "حوض استحمام", sq: "vaskë", tr: "küvet", fr: "baignoire", es: "bañera", it: "vasca da bagno", pl: "wanna" },
  bean: { vi: "đậu", ru: "фасоль", uk: "квасоля", fa: "لوبیا", ar: "فاصوليا", sq: "fasule", tr: "fasulye", fr: "haricot", es: "frijol", it: "fagiolo", pl: "fasola" },
  beautiful: { vi: "đẹp", ru: "красивый", uk: "гарний", fa: "زیبا", ar: "جميل", sq: "i bukur", tr: "güzel", fr: "beau", es: "hermoso", it: "bello", pl: "piękny" },
  bedroom: { vi: "phòng ngủ", ru: "спальня", uk: "спальня", fa: "اتاق خواب", ar: "غرفة نوم", sq: "dhomë gjumi", tr: "yatak odası", fr: "chambre", es: "dormitorio", it: "camera da letto", pl: "sypialnia" },
  bicycle: { vi: "xe đạp", ru: "велосипед", uk: "велосипед", fa: "دوچرخه", ar: "دراجة", sq: "biçikletë", tr: "bisiklet", fr: "vélo", es: "bicicleta", it: "bicicletta", pl: "rower" },
  birthday: { vi: "sinh nhật", ru: "день рождения", uk: "день народження", fa: "تولد", ar: "عيد ميلاد", sq: "ditëlindje", tr: "doğum günü", fr: "anniversaire", es: "cumpleaños", it: "compleanno", pl: "urodziny" },
  black: { vi: "đen", ru: "чёрный", uk: "чорний", fa: "سیاه", ar: "أسود", sq: "i zi", tr: "siyah", fr: "noir", es: "negro", it: "nero", pl: "czarny" },
  blue: { vi: "xanh dương", ru: "синий", uk: "синій", fa: "آبی", ar: "أزرق", sq: "blu", tr: "mavi", fr: "bleu", es: "azul", it: "blu", pl: "niebieski" },
  boy: { vi: "bé trai", ru: "мальчик", uk: "хлопчик", fa: "پسر", ar: "صبي", sq: "djalë", tr: "erkek çocuk", fr: "garçon", es: "niño", it: "ragazzo", pl: "chłopiec" },
  "bread roll": { vi: "bánh mì tròn", ru: "булочка", uk: "булочка", fa: "نان گرد", ar: "لفافة خبز", sq: "simite", tr: "ekmek rulosu", fr: "petit pain", es: "panecillo", it: "panino", pl: "bułka" },
  break: { vi: "giờ nghỉ", ru: "перерыв", uk: "перерва", fa: "استراحت", ar: "استراحة", sq: "pushim", tr: "mola", fr: "pause", es: "descanso", it: "pausa", pl: "przerwa" },
  bring: { vi: "mang", ru: "приносить", uk: "приносити", fa: "آوردن", ar: "يحضر", sq: "sjell", tr: "getirmek", fr: "apporter", es: "traer", it: "portare", pl: "przynosić" },
  broom: { vi: "cây chổi", ru: "метла", uk: "мітла", fa: "جارو", ar: "مكنسة", sq: "fshesë", tr: "süpürge", fr: "balai", es: "escoba", it: "scopa", pl: "miotła" },
  brown: { vi: "nâu", ru: "коричневый", uk: "коричневий", fa: "قهوه‌ای", ar: "بني", sq: "kafe", tr: "kahverengi", fr: "marron", es: "marrón", it: "marrone", pl: "brązowy" },
  brush: { vi: "bàn chải", ru: "щётка", uk: "щітка", fa: "برس", ar: "فرشاة", sq: "furçë", tr: "fırça", fr: "brosse", es: "cepillo", it: "spazzola", pl: "szczotka" },
  bucket: { vi: "xô", ru: "ведро", uk: "відро", fa: "سطل", ar: "دلو", sq: "kovë", tr: "kova", fr: "seau", es: "cubo", it: "secchio", pl: "wiadro" },
  butter: { vi: "bơ", ru: "масло", uk: "масло", fa: "کره", ar: "زبدة", sq: "gjalpë", tr: "tereyağı", fr: "beurre", es: "mantequilla", it: "burro", pl: "masło" },
  cable: { vi: "cáp", ru: "кабель", uk: "кабель", fa: "کابل", ar: "كابل", sq: "kabllo", tr: "kablo", fr: "câble", es: "cable", it: "cavo", pl: "kabel" },
  calm: { vi: "bình tĩnh", ru: "спокойный", uk: "спокійний", fa: "آرام", ar: "هادئ", sq: "i qetë", tr: "sakin", fr: "calme", es: "tranquilo", it: "calmo", pl: "spokojny" },
  can: { vi: "lon", ru: "банка", uk: "бляшанка", fa: "قوطی", ar: "علبة", sq: "kanaçe", tr: "kutu", fr: "canette", es: "lata", it: "lattina", pl: "puszka" },
  car: { vi: "ô tô", ru: "машина", uk: "автомобіль", fa: "ماشین", ar: "سيارة", sq: "makinë", tr: "araba", fr: "voiture", es: "coche", it: "auto", pl: "samochód" },
  ceiling: { vi: "trần nhà", ru: "потолок", uk: "стеля", fa: "سقف", ar: "سقف", sq: "tavan", tr: "tavan", fr: "plafond", es: "techo", it: "soffitto", pl: "sufit" },
  cheap: { vi: "rẻ", ru: "дешёвый", uk: "дешевий", fa: "ارزان", ar: "رخيص", sq: "i lirë", tr: "ucuz", fr: "bon marché", es: "barato", it: "economico", pl: "tani" },
  clear: { vi: "rõ ràng", ru: "ясный", uk: "ясний", fa: "واضح", ar: "واضح", sq: "i qartë", tr: "net", fr: "clair", es: "claro", it: "chiaro", pl: "jasny" },
  clock: { vi: "đồng hồ", ru: "часы", uk: "годинник", fa: "ساعت", ar: "ساعة", sq: "orë", tr: "saat", fr: "horloge", es: "reloj", it: "orologio", pl: "zegar" },
  cloud: { vi: "mây", ru: "облако", uk: "хмара", fa: "ابر", ar: "سحابة", sq: "re", tr: "bulut", fr: "nuage", es: "nube", it: "nuvola", pl: "chmura" },
  colleague: { vi: "đồng nghiệp", ru: "коллега", uk: "колега", fa: "همکار", ar: "زميل", sq: "koleg", tr: "meslektaş", fr: "collègue", es: "colega", it: "collega", pl: "kolega" },
  color: { vi: "màu sắc", ru: "цвет", uk: "колір", fa: "رنگ", ar: "لون", sq: "ngjyrë", tr: "renk", fr: "couleur", es: "color", it: "colore", pl: "kolor" },
  company: { vi: "công ty", ru: "компания", uk: "компанія", fa: "شرکت", ar: "شركة", sq: "kompani", tr: "şirket", fr: "entreprise", es: "empresa", it: "azienda", pl: "firma" },
  cucumber: { vi: "dưa chuột", ru: "огурец", uk: "огірок", fa: "خیار", ar: "خيار", sq: "kastravec", tr: "salatalık", fr: "concombre", es: "pepino", it: "cetriolo", pl: "ogórek" },
  cup: { vi: "cốc", ru: "чашка", uk: "чашка", fa: "فنجان", ar: "كوب", sq: "filxhan", tr: "fincan", fr: "tasse", es: "taza", it: "tazza", pl: "filiżanka" },
  customer: { vi: "khách hàng", ru: "клиент", uk: "клієнт", fa: "مشتری", ar: "زبون", sq: "klient", tr: "müşteri", fr: "client", es: "cliente", it: "cliente", pl: "klient" },
  daughter: { vi: "con gái", ru: "дочь", uk: "донька", fa: "دختر", ar: "ابنة", sq: "vajzë", tr: "kız evlat", fr: "fille", es: "hija", it: "figlia", pl: "córka" },
  difficult: { vi: "khó", ru: "трудный", uk: "важкий", fa: "سخت", ar: "صعب", sq: "i vështirë", tr: "zor", fr: "difficile", es: "difícil", it: "difficile", pl: "trudny" },
  dinner: { vi: "bữa tối", ru: "ужин", uk: "вечеря", fa: "شام", ar: "عشاء", sq: "darkë", tr: "akşam yemeği", fr: "dîner", es: "cena", it: "cena", pl: "kolacja" },
  directly: { vi: "trực tiếp", ru: "сразу", uk: "прямо", fa: "مستقیم", ar: "مباشرة", sq: "drejtpërdrejt", tr: "doğrudan", fr: "directement", es: "directamente", it: "direttamente", pl: "bezpośrednio" },
  doorbell: { vi: "chuông cửa", ru: "дверной звонок", uk: "дверний дзвінок", fa: "زنگ در", ar: "جرس الباب", sq: "zilja e derës", tr: "kapı zili", fr: "sonnette", es: "timbre", it: "campanello", pl: "dzwonek do drzwi" },
  down: { vi: "xuống", ru: "вниз", uk: "вниз", fa: "پایین", ar: "أسفل", sq: "poshtë", tr: "aşağı", fr: "en bas", es: "abajo", it: "giù", pl: "w dół" },
  drawer: { vi: "ngăn kéo", ru: "ящик", uk: "шухляда", fa: "کشو", ar: "درج", sq: "sirtar", tr: "çekmece", fr: "tiroir", es: "cajón", it: "cassetto", pl: "szuflada" },
  driver: { vi: "tài xế", ru: "водитель", uk: "водій", fa: "راننده", ar: "سائق", sq: "shofer", tr: "sürücü", fr: "chauffeur", es: "conductor", it: "autista", pl: "kierowca" },
  ear: { vi: "tai", ru: "ухо", uk: "вухо", fa: "گوش", ar: "أذن", sq: "vesh", tr: "kulak", fr: "oreille", es: "oreja", it: "orecchio", pl: "ucho" },
  early: { vi: "sớm", ru: "рано", uk: "рано", fa: "زود", ar: "مبكر", sq: "herët", tr: "erken", fr: "tôt", es: "temprano", it: "presto", pl: "wcześnie" },
  easy: { vi: "dễ", ru: "лёгкий", uk: "легкий", fa: "آسان", ar: "سهل", sq: "i lehtë", tr: "kolay", fr: "facile", es: "fácil", it: "facile", pl: "łatwy" },
  empty: { vi: "trống", ru: "пустой", uk: "порожній", fa: "خالی", ar: "فارغ", sq: "bosh", tr: "boş", fr: "vide", es: "vacío", it: "vuoto", pl: "pusty" },
  exam: { vi: "kỳ thi", ru: "экзамен", uk: "іспит", fa: "امتحان", ar: "امتحان", sq: "provim", tr: "sınav", fr: "examen", es: "examen", it: "esame", pl: "egzamin" },
  exercise: { vi: "bài tập", ru: "упражнение", uk: "вправа", fa: "تمرین", ar: "تمرين", sq: "ushtrim", tr: "alıştırma", fr: "exercice", es: "ejercicio", it: "esercizio", pl: "ćwiczenie" },
  expensive: { vi: "đắt", ru: "дорогой", uk: "дорогий", fa: "گران", ar: "غالي", sq: "i shtrenjtë", tr: "pahalı", fr: "cher", es: "caro", it: "costoso", pl: "drogi" },
  explain: { vi: "giải thích", ru: "объяснять", uk: "пояснювати", fa: "توضیح دادن", ar: "يشرح", sq: "shpjegoj", tr: "açıklamak", fr: "expliquer", es: "explicar", it: "spiegare", pl: "wyjaśniać" },
  "female doctor": { vi: "nữ bác sĩ", ru: "врач", uk: "лікарка", fa: "پزشک زن", ar: "طبيبة", sq: "mjeke", tr: "kadın doktor", fr: "docteure", es: "doctora", it: "dottoressa", pl: "lekarka" },
  "female friend": { vi: "bạn nữ", ru: "подруга", uk: "подруга", fa: "دوست زن", ar: "صديقة", sq: "shoqe", tr: "kadın arkadaş", fr: "amie", es: "amiga", it: "amica", pl: "przyjaciółka" },
  "female neighbor": { vi: "hàng xóm nữ", ru: "соседка", uk: "сусідка", fa: "همسایه زن", ar: "جارة", sq: "fqinja", tr: "kadın komşu", fr: "voisine", es: "vecina", it: "vicina", pl: "sąsiadka" },
  "female police officer": { vi: "nữ cảnh sát", ru: "женщина-полицейский", uk: "поліцейська", fa: "پلیس زن", ar: "شرطية", sq: "police", tr: "kadın polis", fr: "policière", es: "policía", it: "poliziotta", pl: "policjantka" },
  "female student": { vi: "nữ sinh viên", ru: "студентка", uk: "студентка", fa: "دانشجوی دختر", ar: "طالبة", sq: "studente", tr: "öğrenci kız", fr: "étudiante", es: "estudiante", it: "studentessa", pl: "studentka" },
  "female teacher": { vi: "nữ giáo viên", ru: "учительница", uk: "вчителька", fa: "معلم زن", ar: "معلمة", sq: "mësuese", tr: "kadın öğretmen", fr: "professeure", es: "profesora", it: "insegnante", pl: "nauczycielka" },
  finished: { vi: "xong", ru: "готово", uk: "закінчено", fa: "تمام", ar: "منتهٍ", sq: "i përfunduar", tr: "bitmiş", fr: "terminé", es: "terminado", it: "finito", pl: "skończony" },
  flower: { vi: "hoa", ru: "цветок", uk: "квітка", fa: "گل", ar: "زهرة", sq: "lule", tr: "çiçek", fr: "fleur", es: "flor", it: "fiore", pl: "kwiat" },
  fly: { vi: "bay", ru: "летать", uk: "літати", fa: "پرواز کردن", ar: "يطير", sq: "fluturoj", tr: "uçmak", fr: "voler", es: "volar", it: "volare", pl: "latać" },
  forget: { vi: "quên", ru: "забывать", uk: "забувати", fa: "فراموش کردن", ar: "ينسى", sq: "harroj", tr: "unutmak", fr: "oublier", es: "olvidar", it: "dimenticare", pl: "zapominać" },
  fork: { vi: "nĩa", ru: "вилка", uk: "виделка", fa: "چنگال", ar: "شوكة", sq: "pirun", tr: "çatal", fr: "fourchette", es: "tenedor", it: "forchetta", pl: "widelec" },
  full: { vi: "đầy", ru: "полный", uk: "повний", fa: "پر", ar: "ممتلئ", sq: "plot", tr: "dolu", fr: "plein", es: "lleno", it: "pieno", pl: "pełny" },
  garage: { vi: "ga ra", ru: "гараж", uk: "гараж", fa: "گاراژ", ar: "مرآب", sq: "garazh", tr: "garaj", fr: "garage", es: "garaje", it: "garage", pl: "garaż" },
  garden: { vi: "vườn", ru: "сад", uk: "сад", fa: "باغ", ar: "حديقة", sq: "kopsht", tr: "bahçe", fr: "jardin", es: "jardín", it: "giardino", pl: "ogród" },
  gift: { vi: "quà", ru: "подарок", uk: "подарунок", fa: "هدیه", ar: "هدية", sq: "dhuratë", tr: "hediye", fr: "cadeau", es: "regalo", it: "regalo", pl: "prezent" },
  glass: { vi: "ly", ru: "стакан", uk: "склянка", fa: "لیوان", ar: "كأس", sq: "gotë", tr: "bardak", fr: "verre", es: "vaso", it: "bicchiere", pl: "szklanka" },
  grandfather: { vi: "ông", ru: "дедушка", uk: "дідусь", fa: "پدربزرگ", ar: "جد", sq: "gjysh", tr: "dede", fr: "grand-père", es: "abuelo", it: "nonno", pl: "dziadek" },
  grandmother: { vi: "bà", ru: "бабушка", uk: "бабуся", fa: "مادربزرگ", ar: "جدة", sq: "gjyshe", tr: "büyükanne", fr: "grand-mère", es: "abuela", it: "nonna", pl: "babcia" },
  gray: { vi: "xám", ru: "серый", uk: "сірий", fa: "خاکستری", ar: "رمادي", sq: "gri", tr: "gri", fr: "gris", es: "gris", it: "grigio", pl: "szary" },
  green: { vi: "xanh lá", ru: "зелёный", uk: "зелений", fa: "سبز", ar: "أخضر", sq: "jeshil", tr: "yeşil", fr: "vert", es: "verde", it: "verde", pl: "zielony" },
  ham: { vi: "giăm bông", ru: "ветчина", uk: "шинка", fa: "ژامبون", ar: "لحم خنزير", sq: "proshutë", tr: "jambon", fr: "jambon", es: "jamón", it: "prosciutto", pl: "szynka" },
  healthy: { vi: "khỏe mạnh", ru: "здоровый", uk: "здоровий", fa: "سالم", ar: "صحي", sq: "i shëndetshëm", tr: "sağlıklı", fr: "sain", es: "saludable", it: "sano", pl: "zdrowy" },
  hotel: { vi: "khách sạn", ru: "отель", uk: "готель", fa: "هتل", ar: "فندق", sq: "hotel", tr: "otel", fr: "hôtel", es: "hotel", it: "hotel", pl: "hotel" },
  hungry: { vi: "đói", ru: "голодный", uk: "голодний", fa: "گرسنه", ar: "جائع", sq: "i uritur", tr: "aç", fr: "affamé", es: "hambriento", it: "affamato", pl: "głodny" },
  "ice cream": { vi: "kem", ru: "мороженое", uk: "морозиво", fa: "بستنی", ar: "آيس كريم", sq: "akullore", tr: "dondurma", fr: "glace", es: "helado", it: "gelato", pl: "lody" },
  "identity card": { vi: "thẻ căn cước", ru: "удостоверение личности", uk: "посвідчення особи", fa: "کارت شناسایی", ar: "بطاقة هوية", sq: "kartë identiteti", tr: "kimlik kartı", fr: "carte d'identité", es: "documento de identidad", it: "carta d'identità", pl: "dowód osobisty" },
  important: { vi: "quan trọng", ru: "важный", uk: "важливий", fa: "مهم", ar: "مهم", sq: "i rëndësishëm", tr: "önemli", fr: "important", es: "importante", it: "importante", pl: "ważny" },
  inside: { vi: "bên trong", ru: "внутри", uk: "всередині", fa: "داخل", ar: "داخل", sq: "brenda", tr: "içeride", fr: "à l'intérieur", es: "dentro", it: "dentro", pl: "w środku" },
  jam: { vi: "mứt", ru: "джем", uk: "джем", fa: "مربا", ar: "مربى", sq: "reçel", tr: "reçel", fr: "confiture", es: "mermelada", it: "marmellata", pl: "dżem" },
  knife: { vi: "dao", ru: "нож", uk: "ніж", fa: "چاقو", ar: "سكين", sq: "thikë", tr: "bıçak", fr: "couteau", es: "cuchillo", it: "coltello", pl: "nóż" },
  later: { vi: "sau", ru: "позже", uk: "пізніше", fa: "بعداً", ar: "لاحقاً", sq: "më vonë", tr: "sonra", fr: "plus tard", es: "más tarde", it: "più tardi", pl: "później" },
  leg: { vi: "chân", ru: "нога", uk: "нога", fa: "پا", ar: "ساق", sq: "këmbë", tr: "bacak", fr: "jambe", es: "pierna", it: "gamba", pl: "noga" },
  lemon: { vi: "chanh", ru: "лимон", uk: "лимон", fa: "لیمو", ar: "ليمون", sq: "limon", tr: "limon", fr: "citron", es: "limón", it: "limone", pl: "cytryna" },
  light: { vi: "ánh sáng", ru: "свет", uk: "світло", fa: "نور", ar: "ضوء", sq: "dritë", tr: "ışık", fr: "lumière", es: "luz", it: "luce", pl: "światło" },
  "living room": { vi: "phòng khách", ru: "гостиная", uk: "вітальня", fa: "اتاق نشیمن", ar: "غرفة المعيشة", sq: "dhomë ndenjeje", tr: "oturma odası", fr: "salon", es: "sala de estar", it: "soggiorno", pl: "salon" },
  lock: { vi: "ổ khóa", ru: "замок", uk: "замок", fa: "قفل", ar: "قفل", sq: "bravë", tr: "kilit", fr: "serrure", es: "cerradura", it: "serratura", pl: "zamek" },
  loud: { vi: "ồn ào", ru: "громкий", uk: "гучний", fa: "بلند", ar: "صاخب", sq: "i zhurmshëm", tr: "gürültülü", fr: "fort", es: "ruidoso", it: "rumoroso", pl: "głośny" },
  lunch: { vi: "bữa trưa", ru: "обед", uk: "обід", fa: "ناهار", ar: "غداء", sq: "drekë", tr: "öğle yemeği", fr: "déjeuner", es: "almuerzo", it: "pranzo", pl: "obiad" },
  man: { vi: "đàn ông", ru: "мужчина", uk: "чоловік", fa: "مرد", ar: "رجل", sq: "burrë", tr: "adam", fr: "homme", es: "hombre", it: "uomo", pl: "mężczyzna" },
  map: { vi: "bản đồ", ru: "карта", uk: "карта", fa: "نقشه", ar: "خريطة", sq: "hartë", tr: "harita", fr: "carte", es: "mapa", it: "mappa", pl: "mapa" },
  mattress: { vi: "nệm", ru: "матрас", uk: "матрац", fa: "تشک", ar: "مرتبة", sq: "dyshek", tr: "yatak", fr: "matelas", es: "colchón", it: "materasso", pl: "materac" },
  maybe: { vi: "có lẽ", ru: "может быть", uk: "можливо", fa: "شاید", ar: "ربما", sq: "ndoshta", tr: "belki", fr: "peut-être", es: "quizás", it: "forse", pl: "może" },
  meal: { vi: "bữa ăn", ru: "приём пищи", uk: "прийом їжі", fa: "وعده غذایی", ar: "وجبة", sq: "vakt", tr: "öğün", fr: "repas", es: "comida", it: "pasto", pl: "posiłek" },
  meat: { vi: "thịt", ru: "мясо", uk: "м'ясо", fa: "گوشت", ar: "لحم", sq: "mish", tr: "et", fr: "viande", es: "carne", it: "carne", pl: "mięso" },
  menu: { vi: "thực đơn", ru: "меню", uk: "меню", fa: "منو", ar: "قائمة", sq: "menu", tr: "menü", fr: "menu", es: "menú", it: "menù", pl: "menu" },
  mountain: { vi: "núi", ru: "гора", uk: "гора", fa: "کوه", ar: "جبل", sq: "mal", tr: "dağ", fr: "montagne", es: "montaña", it: "montagna", pl: "góra" },
  movie: { vi: "phim", ru: "фильм", uk: "фільм", fa: "فیلم", ar: "فيلم", sq: "film", tr: "film", fr: "film", es: "película", it: "film", pl: "film" },
  muesli: { vi: "ngũ cốc muesli", ru: "мюсли", uk: "мюслі", fa: "موسلی", ar: "موسلي", sq: "muesli", tr: "müsli", fr: "muesli", es: "muesli", it: "muesli", pl: "musli" },
  music: { vi: "âm nhạc", ru: "музыка", uk: "музика", fa: "موسیقی", ar: "موسيقى", sq: "muzikë", tr: "müzik", fr: "musique", es: "música", it: "musica", pl: "muzyka" },
  neighbor: { vi: "hàng xóm", ru: "сосед", uk: "сусід", fa: "همسایه", ar: "جار", sq: "fqinj", tr: "komşu", fr: "voisin", es: "vecino", it: "vicino", pl: "sąsiad" },
  nervous: { vi: "lo lắng", ru: "нервный", uk: "нервовий", fa: "عصبی", ar: "متوتر", sq: "nervoz", tr: "gergin", fr: "nerveux", es: "nervioso", it: "nervoso", pl: "nerwowy" },
  office: { vi: "văn phòng", ru: "офис", uk: "офіс", fa: "دفتر", ar: "مكتب", sq: "zyrë", tr: "ofis", fr: "bureau", es: "oficina", it: "ufficio", pl: "biuro" },
  often: { vi: "thường xuyên", ru: "часто", uk: "часто", fa: "اغلب", ar: "غالباً", sq: "shpesh", tr: "sık sık", fr: "souvent", es: "a menudo", it: "spesso", pl: "często" },
  oil: { vi: "dầu", ru: "масло", uk: "олія", fa: "روغن", ar: "زيت", sq: "vaj", tr: "yağ", fr: "huile", es: "aceite", it: "olio", pl: "olej" },
  outside: { vi: "bên ngoài", ru: "снаружи", uk: "зовні", fa: "بیرون", ar: "خارج", sq: "jashtë", tr: "dışarıda", fr: "dehors", es: "fuera", it: "fuori", pl: "na zewnątrz" },
  package: { vi: "bưu kiện", ru: "посылка", uk: "пакунок", fa: "بسته", ar: "طرد", sq: "paketë", tr: "paket", fr: "colis", es: "paquete", it: "pacco", pl: "paczka" },
  pan: { vi: "chảo", ru: "сковорода", uk: "сковорода", fa: "ماهیتابه", ar: "مقلاة", sq: "tigan", tr: "tava", fr: "poêle", es: "sartén", it: "padella", pl: "patelnia" },
  party: { vi: "bữa tiệc", ru: "вечеринка", uk: "вечірка", fa: "مهمانی", ar: "حفلة", sq: "festë", tr: "parti", fr: "fête", es: "fiesta", it: "festa", pl: "impreza" },
  pepper: { vi: "tiêu", ru: "перец", uk: "перець", fa: "فلفل", ar: "فلفل", sq: "piper", tr: "biber", fr: "poivre", es: "pimienta", it: "pepe", pl: "pieprz" },
  photo: { vi: "ảnh", ru: "фото", uk: "фото", fa: "عکس", ar: "صورة", sq: "foto", tr: "fotoğraf", fr: "photo", es: "foto", it: "foto", pl: "zdjęcie" },
  picture: { vi: "hình ảnh", ru: "картинка", uk: "зображення", fa: "تصویر", ar: "صورة", sq: "figurë", tr: "resim", fr: "image", es: "imagen", it: "immagine", pl: "obraz" },
  pillow: { vi: "gối", ru: "подушка", uk: "подушка", fa: "بالش", ar: "وسادة", sq: "jastëk", tr: "yastık", fr: "oreiller", es: "almohada", it: "cuscino", pl: "poduszka" },
  pink: { vi: "hồng", ru: "розовый", uk: "рожевий", fa: "صورتی", ar: "وردي", sq: "rozë", tr: "pembe", fr: "rose", es: "rosa", it: "rosa", pl: "różowy" },
  plan: { vi: "kế hoạch", ru: "план", uk: "план", fa: "برنامه", ar: "خطة", sq: "plan", tr: "plan", fr: "plan", es: "plan", it: "piano", pl: "plan" },
  plate: { vi: "đĩa", ru: "тарелка", uk: "тарілка", fa: "بشقاب", ar: "طبق", sq: "pjatë", tr: "tabak", fr: "assiette", es: "plato", it: "piatto", pl: "talerz" },
  "police officer": { vi: "cảnh sát", ru: "полицейский", uk: "поліцейський", fa: "پلیس", ar: "شرطي", sq: "polic", tr: "polis", fr: "policier", es: "policía", it: "poliziotto", pl: "policjant" },
  poster: { vi: "áp phích", ru: "плакат", uk: "плакат", fa: "پوستر", ar: "ملصق", sq: "poster", tr: "poster", fr: "affiche", es: "póster", it: "poster", pl: "plakat" },
  questionnaire: { vi: "bảng câu hỏi", ru: "опросник", uk: "опитувальник", fa: "پرسشنامه", ar: "استبيان", sq: "pyetësor", tr: "anket", fr: "questionnaire", es: "cuestionario", it: "questionario", pl: "kwestionariusz" },
  quiet: { vi: "yên tĩnh", ru: "тихий", uk: "тихий", fa: "ساکت", ar: "هادئ", sq: "i qetë", tr: "sessiz", fr: "silencieux", es: "silencioso", it: "silenzioso", pl: "cichy" },
  radio: { vi: "radio", ru: "радио", uk: "радіо", fa: "رادیو", ar: "راديو", sq: "radio", tr: "radyo", fr: "radio", es: "radio", it: "radio", pl: "radio" },
  rain: { vi: "mưa", ru: "дождь", uk: "дощ", fa: "باران", ar: "مطر", sq: "shi", tr: "yağmur", fr: "pluie", es: "lluvia", it: "pioggia", pl: "deszcz" },
  really: { vi: "thực sự", ru: "действительно", uk: "справді", fa: "واقعاً", ar: "حقاً", sq: "vërtet", tr: "gerçekten", fr: "vraiment", es: "realmente", it: "davvero", pl: "naprawdę" },
  recipe: { vi: "công thức", ru: "рецепт", uk: "рецепт", fa: "دستور پخت", ar: "وصفة", sq: "recetë", tr: "tarif", fr: "recette", es: "receta", it: "ricetta", pl: "przepis" },
  red: { vi: "đỏ", ru: "красный", uk: "червоний", fa: "قرمز", ar: "أحمر", sq: "e kuqe", tr: "kırmızı", fr: "rouge", es: "rojo", it: "rosso", pl: "czerwony" },
  refrigerator: { vi: "tủ lạnh", ru: "холодильник", uk: "холодильник", fa: "یخچال", ar: "ثلاجة", sq: "frigorifer", tr: "buzdolabı", fr: "réfrigérateur", es: "refrigerador", it: "frigorifero", pl: "lodówka" },
  remember: { vi: "nhớ", ru: "помнить", uk: "пам'ятати", fa: "به یاد آوردن", ar: "يتذكر", sq: "mbaj mend", tr: "hatırlamak", fr: "se souvenir", es: "recordar", it: "ricordare", pl: "pamiętać" },
  "remote control": { vi: "điều khiển từ xa", ru: "пульт дистанционного управления", uk: "пульт дистанційного керування", fa: "کنترل از راه دور", ar: "جهاز تحكم عن بعد", sq: "telekomandë", tr: "uzaktan kumanda", fr: "télécommande", es: "mando a distancia", it: "telecomando", pl: "pilot" },
  river: { vi: "sông", ru: "река", uk: "річка", fa: "رودخانه", ar: "نهر", sq: "lumë", tr: "nehir", fr: "rivière", es: "río", it: "fiume", pl: "rzeka" },
  roof: { vi: "mái nhà", ru: "крыша", uk: "дах", fa: "سقف", ar: "سقف", sq: "çati", tr: "çatı", fr: "toit", es: "tejado", it: "tetto", pl: "dach" },
  "room number": { vi: "số phòng", ru: "номер комнаты", uk: "номер кімнати", fa: "شماره اتاق", ar: "رقم الغرفة", sq: "numri i dhomës", tr: "oda numarası", fr: "numéro de chambre", es: "número de habitación", it: "numero della camera", pl: "numer pokoju" },
  saleswoman: { vi: "nữ bán hàng", ru: "продавщица", uk: "продавчиня", fa: "فروشنده زن", ar: "بائعة", sq: "shitëse", tr: "kadın satıcı", fr: "vendeuse", es: "vendedora", it: "commessa", pl: "sprzedawczyni" },
  salt: { vi: "muối", ru: "соль", uk: "сіль", fa: "نمک", ar: "ملح", sq: "kripë", tr: "tuz", fr: "sel", es: "sal", it: "sale", pl: "sól" },
  sandwich: { vi: "bánh sandwich", ru: "сэндвич", uk: "сендвіч", fa: "ساندویچ", ar: "شطيرة", sq: "sanduiç", tr: "sandviç", fr: "sandwich", es: "sándwich", it: "panino", pl: "kanapka" },
  sausage: { vi: "xúc xích", ru: "колбаса", uk: "ковбаса", fa: "سوسیس", ar: "نقانق", sq: "sallam", tr: "sosis", fr: "saucisse", es: "salchicha", it: "salsiccia", pl: "kiełbasa" },
  screen: { vi: "màn hình", ru: "экран", uk: "екран", fa: "صفحه نمایش", ar: "شاشة", sq: "ekran", tr: "ekran", fr: "écran", es: "pantalla", it: "schermo", pl: "ekran" },
  sea: { vi: "biển", ru: "море", uk: "море", fa: "دریا", ar: "بحر", sq: "det", tr: "deniz", fr: "mer", es: "mar", it: "mare", pl: "morze" },
  seller: { vi: "người bán", ru: "продавец", uk: "продавець", fa: "فروشنده", ar: "بائع", sq: "shitës", tr: "satıcı", fr: "vendeur", es: "vendedor", it: "venditore", pl: "sprzedawca" },
  shelf: { vi: "kệ", ru: "полка", uk: "полиця", fa: "قفسه", ar: "رف", sq: "raft", tr: "raf", fr: "étagère", es: "estante", it: "scaffale", pl: "półka" },
  shower: { vi: "vòi hoa sen", ru: "душ", uk: "душ", fa: "دوش", ar: "دش", sq: "dush", tr: "duş", fr: "douche", es: "ducha", it: "doccia", pl: "prysznic" },
  sick: { vi: "ốm", ru: "больной", uk: "хворий", fa: "بیمار", ar: "مريض", sq: "i sëmurë", tr: "hasta", fr: "malade", es: "enfermo", it: "malato", pl: "chory" },
  sink: { vi: "bồn rửa", ru: "раковина", uk: "раковина", fa: "سینک", ar: "مغسلة", sq: "lavaman", tr: "lavabo", fr: "évier", es: "fregadero", it: "lavandino", pl: "zlew" },
  snow: { vi: "tuyết", ru: "снег", uk: "сніг", fa: "برف", ar: "ثلج", sq: "borë", tr: "kar", fr: "neige", es: "nieve", it: "neve", pl: "śnieg" },
  soap: { vi: "xà phòng", ru: "мыло", uk: "мило", fa: "صابون", ar: "صابون", sq: "sapun", tr: "sabun", fr: "savon", es: "jabón", it: "sapone", pl: "mydło" },
  socket: { vi: "ổ cắm", ru: "розетка", uk: "розетка", fa: "پریز", ar: "مقبس", sq: "prizë", tr: "priz", fr: "prise", es: "enchufe", it: "presa", pl: "gniazdko" },
  sofa: { vi: "ghế sofa", ru: "диван", uk: "диван", fa: "مبل", ar: "أريكة", sq: "divan", tr: "kanepe", fr: "canapé", es: "sofá", it: "divano", pl: "sofa" },
  sometimes: { vi: "đôi khi", ru: "иногда", uk: "іноді", fa: "گاهی", ar: "أحياناً", sq: "ndonjëherë", tr: "bazen", fr: "parfois", es: "a veces", it: "a volte", pl: "czasami" },
  song: { vi: "bài hát", ru: "песня", uk: "пісня", fa: "ترانه", ar: "أغنية", sq: "këngë", tr: "şarkı", fr: "chanson", es: "canción", it: "canzone", pl: "piosenka" },
  soon: { vi: "sớm thôi", ru: "скоро", uk: "скоро", fa: "به زودی", ar: "قريباً", sq: "së shpejti", tr: "yakında", fr: "bientôt", es: "pronto", it: "presto", pl: "wkrótce" },
  spoon: { vi: "thìa", ru: "ложка", uk: "ложка", fa: "قاشق", ar: "ملعقة", sq: "lugë", tr: "kaşık", fr: "cuillère", es: "cuchara", it: "cucchiaio", pl: "łyżka" },
  spring: { vi: "mùa xuân", ru: "весна", uk: "весна", fa: "بهار", ar: "ربيع", sq: "pranverë", tr: "ilkbahar", fr: "printemps", es: "primavera", it: "primavera", pl: "wiosna" },
  square: { vi: "quảng trường", ru: "площадь", uk: "площа", fa: "میدان", ar: "ساحة", sq: "shesh", tr: "meydan", fr: "place", es: "plaza", it: "piazza", pl: "plac" },
  stairs: { vi: "cầu thang", ru: "лестница", uk: "сходи", fa: "پله", ar: "درج", sq: "shkallë", tr: "merdiven", fr: "escalier", es: "escaleras", it: "scale", pl: "schody" },
  station: { vi: "ga", ru: "станция", uk: "станція", fa: "ایستگاه", ar: "محطة", sq: "stacion", tr: "istasyon", fr: "gare", es: "estación", it: "stazione", pl: "stacja" },
  stove: { vi: "bếp", ru: "плита", uk: "плита", fa: "اجاق", ar: "موقد", sq: "sobë", tr: "ocak", fr: "cuisinière", es: "estufa", it: "fornello", pl: "kuchenka" },
  street: { vi: "đường phố", ru: "улица", uk: "вулиця", fa: "خیابان", ar: "شارع", sq: "rrugë", tr: "sokak", fr: "rue", es: "calle", it: "strada", pl: "ulica" },
  suitcase: { vi: "va li", ru: "чемодан", uk: "валіза", fa: "چمدان", ar: "حقيبة سفر", sq: "valixhe", tr: "bavul", fr: "valise", es: "maleta", it: "valigia", pl: "walizka" },
  sun: { vi: "mặt trời", ru: "солнце", uk: "сонце", fa: "خورشید", ar: "شمس", sq: "diell", tr: "güneş", fr: "soleil", es: "sol", it: "sole", pl: "słońce" },
  switch: { vi: "công tắc", ru: "выключатель", uk: "вимикач", fa: "کلید برق", ar: "مفتاح", sq: "ndërprerës", tr: "anahtar", fr: "interrupteur", es: "interruptor", it: "interruttore", pl: "włącznik" },
  tablet: { vi: "máy tính bảng", ru: "планшет", uk: "планшет", fa: "تبلت", ar: "جهاز لوحي", sq: "tablet", tr: "tablet", fr: "tablette", es: "tableta", it: "tablet", pl: "tablet" },
  "take along": { vi: "mang theo", ru: "брать с собой", uk: "брати з собою", fa: "با خود بردن", ar: "يأخذ معه", sq: "marr me vete", tr: "yanında götürmek", fr: "emmener", es: "llevar consigo", it: "portare con sé", pl: "zabrać ze sobą" },
  task: { vi: "nhiệm vụ", ru: "задача", uk: "завдання", fa: "وظیفه", ar: "مهمة", sq: "detyrë", tr: "görev", fr: "tâche", es: "tarea", it: "compito", pl: "zadanie" },
  taxi: { vi: "taxi", ru: "такси", uk: "таксі", fa: "تاکسی", ar: "تاكسي", sq: "taksi", tr: "taksi", fr: "taxi", es: "taxi", it: "taxi", pl: "taksówka" },
  thirsty: { vi: "khát", ru: "хочу пить", uk: "спраглий", fa: "تشنه", ar: "عطشان", sq: "i etur", tr: "susamış", fr: "assoiffé", es: "sediento", it: "assetato", pl: "spragniony" },
  "ticket inspection": { vi: "kiểm tra vé", ru: "контроль билетов", uk: "перевірка квитків", fa: "بازرسی بلیت", ar: "تفتيش التذاكر", sq: "kontrolli i biletave", tr: "bilet kontrolü", fr: "contrôle des billets", es: "control de billetes", it: "controllo dei biglietti", pl: "kontrola biletów" },
  tired: { vi: "mệt", ru: "усталый", uk: "втомлений", fa: "خسته", ar: "متعب", sq: "i lodhur", tr: "yorgun", fr: "fatigué", es: "cansado", it: "stanco", pl: "zmęczony" },
  tool: { vi: "công cụ", ru: "инструмент", uk: "інструмент", fa: "ابزار", ar: "أداة", sq: "mjet", tr: "alet", fr: "outil", es: "herramienta", it: "attrezzo", pl: "narzędzie" },
  towel: { vi: "khăn tắm", ru: "полотенце", uk: "рушник", fa: "حوله", ar: "منشفة", sq: "peshqir", tr: "havlu", fr: "serviette", es: "toalla", it: "asciugamano", pl: "ręcznik" },
  toy: { vi: "đồ chơi", ru: "игрушка", uk: "іграшка", fa: "اسباب‌بازی", ar: "لعبة", sq: "lodër", tr: "oyuncak", fr: "jouet", es: "juguete", it: "giocattolo", pl: "zabawka" },
  "traffic light": { vi: "đèn giao thông", ru: "светофор", uk: "світлофор", fa: "چراغ راهنمایی", ar: "إشارة مرور", sq: "semafor", tr: "trafik ışığı", fr: "feu de circulation", es: "semáforo", it: "semaforo", pl: "sygnalizacja świetlna" },
  tree: { vi: "cây", ru: "дерево", uk: "дерево", fa: "درخت", ar: "شجرة", sq: "pemë", tr: "ağaç", fr: "arbre", es: "árbol", it: "albero", pl: "drzewo" },
  "turn off": { vi: "tắt", ru: "выключать", uk: "вимикати", fa: "خاموش کردن", ar: "يطفئ", sq: "fik", tr: "kapatmak", fr: "éteindre", es: "apagar", it: "spegnere", pl: "wyłączyć" },
  "turn on": { vi: "bật", ru: "включать", uk: "вмикати", fa: "روشن کردن", ar: "يشغل", sq: "ndez", tr: "açmak", fr: "allumer", es: "encender", it: "accendere", pl: "włączyć" },
  ugly: { vi: "xấu", ru: "некрасивый", uk: "потворний", fa: "زشت", ar: "قبيح", sq: "i shëmtuar", tr: "çirkin", fr: "laid", es: "feo", it: "brutto", pl: "brzydki" },
  umbrella: { vi: "ô", ru: "зонт", uk: "парасоля", fa: "چتر", ar: "مظلة", sq: "çadër", tr: "şemsiye", fr: "parapluie", es: "paraguas", it: "ombrello", pl: "parasol" },
  up: { vi: "lên", ru: "вверх", uk: "вгору", fa: "بالا", ar: "أعلى", sq: "lart", tr: "yukarı", fr: "en haut", es: "arriba", it: "su", pl: "w górę" },
  vacation: { vi: "kỳ nghỉ", ru: "отпуск", uk: "відпустка", fa: "تعطیلات", ar: "عطلة", sq: "pushime", tr: "tatil", fr: "vacances", es: "vacaciones", it: "vacanza", pl: "wakacje" },
  visit: { vi: "thăm", ru: "посещать", uk: "відвідувати", fa: "دیدار کردن", ar: "يزور", sq: "vizitoj", tr: "ziyaret etmek", fr: "visiter", es: "visitar", it: "visitare", pl: "odwiedzać" },
  visitor: { vi: "khách thăm", ru: "посетитель", uk: "відвідувач", fa: "بازدیدکننده", ar: "زائر", sq: "vizitor", tr: "ziyaretçi", fr: "visiteur", es: "visitante", it: "visitatore", pl: "odwiedzający" },
  waiter: { vi: "bồi bàn", ru: "официант", uk: "офіціант", fa: "پیشخدمت", ar: "نادل", sq: "kamerier", tr: "garson", fr: "serveur", es: "camarero", it: "cameriere", pl: "kelner" },
  wall: { vi: "tường", ru: "стена", uk: "стіна", fa: "دیوار", ar: "جدار", sq: "mur", tr: "duvar", fr: "mur", es: "pared", it: "parete", pl: "ściana" },
  "washing machine": { vi: "máy giặt", ru: "стиральная машина", uk: "пральна машина", fa: "ماشین لباسشویی", ar: "غسالة", sq: "lavatriçe", tr: "çamaşır makinesi", fr: "machine à laver", es: "lavadora", it: "lavatrice", pl: "pralka" },
  weather: { vi: "thời tiết", ru: "погода", uk: "погода", fa: "آب و هوا", ar: "طقس", sq: "moti", tr: "hava durumu", fr: "météo", es: "clima", it: "tempo", pl: "pogoda" },
  white: { vi: "trắng", ru: "белый", uk: "білий", fa: "سفید", ar: "أبيض", sq: "i bardhë", tr: "beyaz", fr: "blanc", es: "blanco", it: "bianco", pl: "biały" },
  wind: { vi: "gió", ru: "ветер", uk: "вітер", fa: "باد", ar: "ريح", sq: "erë", tr: "rüzgar", fr: "vent", es: "viento", it: "vento", pl: "wiatr" },
  winter: { vi: "mùa đông", ru: "зима", uk: "зима", fa: "زمستان", ar: "شتاء", sq: "dimër", tr: "kış", fr: "hiver", es: "invierno", it: "inverno", pl: "zima" },
  yellow: { vi: "vàng", ru: "жёлтый", uk: "жовтий", fa: "زرد", ar: "أصفر", sq: "e verdhë", tr: "sarı", fr: "jaune", es: "amarillo", it: "giallo", pl: "żółty" },
  young: { vi: "trẻ", ru: "молодой", uk: "молодий", fa: "جوان", ar: "شاب", sq: "i ri", tr: "genç", fr: "jeune", es: "joven", it: "giovane", pl: "młody" },
};

Object.assign(MINI_GAMES_GLOSSARY, MINI_GAMES_GLOSSARY_EXTRA);

export function getMiniGamesGloss(gloss: string, locale: string): string {
  const normalizedLocale = LOCALE_SET.has(locale as MiniGamesGlossaryLocale)
    ? (locale as MiniGamesGlossaryLocale)
    : "en";
  const contentLocale = normalizedLocale === "de" ? "en" : normalizedLocale;
  return MINI_GAMES_GLOSSARY[gloss]?.[contentLocale] ?? gloss;
}

export function hasMiniGamesGloss(gloss: string, locale: string): boolean {
  const normalizedLocale = LOCALE_SET.has(locale as MiniGamesGlossaryLocale)
    ? (locale as MiniGamesGlossaryLocale)
    : "en";
  if (normalizedLocale === "en" || normalizedLocale === "de") return true;
  return Boolean(MINI_GAMES_GLOSSARY[gloss]?.[normalizedLocale]);
}
